/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktasks.h"

static const char* CMockString_delay_ms = "delay_ms";
static const char* CMockString_hal_tasks_init = "hal_tasks_init";
static const char* CMockString_hal_tasks_schedule = "hal_tasks_schedule";
static const char* CMockString_hal_tasks_unschedule = "hal_tasks_unschedule";
static const char* CMockString_task = "task";

typedef struct _CMOCK_hal_tasks_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_task_t* Expected_task;
  int Expected_task_Depth;

} CMOCK_hal_tasks_init_CALL_INSTANCE;

typedef struct _CMOCK_hal_tasks_schedule_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_task_t* Expected_task;
  uint32_t Expected_delay_ms;
  int Expected_task_Depth;

} CMOCK_hal_tasks_schedule_CALL_INSTANCE;

typedef struct _CMOCK_hal_tasks_unschedule_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_task_t* Expected_task;
  int Expected_task_Depth;

} CMOCK_hal_tasks_unschedule_CALL_INSTANCE;

static struct MocktasksInstance
{
  char hal_tasks_init_IgnoreBool;
  char hal_tasks_init_CallbackBool;
  CMOCK_hal_tasks_init_CALLBACK hal_tasks_init_CallbackFunctionPointer;
  int hal_tasks_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_tasks_init_CallInstance;
  char hal_tasks_schedule_IgnoreBool;
  char hal_tasks_schedule_CallbackBool;
  CMOCK_hal_tasks_schedule_CALLBACK hal_tasks_schedule_CallbackFunctionPointer;
  int hal_tasks_schedule_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_tasks_schedule_CallInstance;
  char hal_tasks_unschedule_IgnoreBool;
  char hal_tasks_unschedule_CallbackBool;
  CMOCK_hal_tasks_unschedule_CALLBACK hal_tasks_unschedule_CallbackFunctionPointer;
  int hal_tasks_unschedule_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_tasks_unschedule_CallInstance;
} Mock;


void Mocktasks_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.hal_tasks_init_CallInstance;
  if (Mock.hal_tasks_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_tasks_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_tasks_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_tasks_schedule_CallInstance;
  if (Mock.hal_tasks_schedule_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_tasks_schedule);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_tasks_schedule_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_tasks_unschedule_CallInstance;
  if (Mock.hal_tasks_unschedule_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_tasks_unschedule);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_tasks_unschedule_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocktasks_Init(void)
{
  Mocktasks_Destroy();
}

void Mocktasks_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void hal_tasks_init(hal_task_t* task)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_tasks_init);
  cmock_call_instance = (CMOCK_hal_tasks_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_tasks_init_CallInstance);
  Mock.hal_tasks_init_CallInstance = CMock_Guts_MemNext(Mock.hal_tasks_init_CallInstance);
  if (Mock.hal_tasks_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_tasks_init_CallbackBool &&
      Mock.hal_tasks_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_init_CallbackFunctionPointer(task, Mock.hal_tasks_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_tasks_init,CMockString_task);
    if (cmock_call_instance->Expected_task == NULL)
      { UNITY_TEST_ASSERT_NULL(task, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_task), (void*)(task), sizeof(hal_task_t), cmock_call_instance->Expected_task_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.hal_tasks_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_init_CallbackFunctionPointer(task, Mock.hal_tasks_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_tasks_init(CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth);
void CMockExpectParameters_hal_tasks_init(CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth)
{
  cmock_call_instance->Expected_task = task;
  cmock_call_instance->Expected_task_Depth = task_Depth;
}

void hal_tasks_init_CMockIgnore(void)
{
  Mock.hal_tasks_init_IgnoreBool = (char)1;
}

void hal_tasks_init_CMockStopIgnore(void)
{
  Mock.hal_tasks_init_IgnoreBool = (char)0;
}

void hal_tasks_init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_init_CALL_INSTANCE));
  CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_init_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_init_CallInstance, cmock_guts_index);
  Mock.hal_tasks_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_tasks_init_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_init_CALL_INSTANCE));
  CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_init_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_init_CallInstance, cmock_guts_index);
  Mock.hal_tasks_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_init(cmock_call_instance, task, 1);
}

void hal_tasks_init_AddCallback(CMOCK_hal_tasks_init_CALLBACK Callback)
{
  Mock.hal_tasks_init_IgnoreBool = (char)0;
  Mock.hal_tasks_init_CallbackBool = (char)1;
  Mock.hal_tasks_init_CallbackFunctionPointer = Callback;
}

void hal_tasks_init_Stub(CMOCK_hal_tasks_init_CALLBACK Callback)
{
  Mock.hal_tasks_init_IgnoreBool = (char)0;
  Mock.hal_tasks_init_CallbackBool = (char)0;
  Mock.hal_tasks_init_CallbackFunctionPointer = Callback;
}

void hal_tasks_init_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_init_CALL_INSTANCE));
  CMOCK_hal_tasks_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_init_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_init_CallInstance, cmock_guts_index);
  Mock.hal_tasks_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_init(cmock_call_instance, task, task_Depth);
}

void hal_tasks_schedule(hal_task_t* task, uint32_t delay_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_tasks_schedule);
  cmock_call_instance = (CMOCK_hal_tasks_schedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_tasks_schedule_CallInstance);
  Mock.hal_tasks_schedule_CallInstance = CMock_Guts_MemNext(Mock.hal_tasks_schedule_CallInstance);
  if (Mock.hal_tasks_schedule_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_tasks_schedule_CallbackBool &&
      Mock.hal_tasks_schedule_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_schedule_CallbackFunctionPointer(task, delay_ms, Mock.hal_tasks_schedule_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_tasks_schedule,CMockString_task);
    if (cmock_call_instance->Expected_task == NULL)
      { UNITY_TEST_ASSERT_NULL(task, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_task), (void*)(task), sizeof(hal_task_t), cmock_call_instance->Expected_task_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_tasks_schedule,CMockString_delay_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_delay_ms, delay_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_tasks_schedule_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_schedule_CallbackFunctionPointer(task, delay_ms, Mock.hal_tasks_schedule_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_tasks_schedule(CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth, uint32_t delay_ms);
void CMockExpectParameters_hal_tasks_schedule(CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth, uint32_t delay_ms)
{
  cmock_call_instance->Expected_task = task;
  cmock_call_instance->Expected_task_Depth = task_Depth;
  cmock_call_instance->Expected_delay_ms = delay_ms;
}

void hal_tasks_schedule_CMockIgnore(void)
{
  Mock.hal_tasks_schedule_IgnoreBool = (char)1;
}

void hal_tasks_schedule_CMockStopIgnore(void)
{
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
}

void hal_tasks_schedule_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_schedule_CALL_INSTANCE));
  CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_schedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_schedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_schedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_tasks_schedule_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task, uint32_t delay_ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_schedule_CALL_INSTANCE));
  CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_schedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_schedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_schedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_schedule(cmock_call_instance, task, 1, delay_ms);
}

void hal_tasks_schedule_AddCallback(CMOCK_hal_tasks_schedule_CALLBACK Callback)
{
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
  Mock.hal_tasks_schedule_CallbackBool = (char)1;
  Mock.hal_tasks_schedule_CallbackFunctionPointer = Callback;
}

void hal_tasks_schedule_Stub(CMOCK_hal_tasks_schedule_CALLBACK Callback)
{
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
  Mock.hal_tasks_schedule_CallbackBool = (char)0;
  Mock.hal_tasks_schedule_CallbackFunctionPointer = Callback;
}

void hal_tasks_schedule_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth, uint32_t delay_ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_schedule_CALL_INSTANCE));
  CMOCK_hal_tasks_schedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_schedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_schedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_schedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_schedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_schedule(cmock_call_instance, task, task_Depth, delay_ms);
}

void hal_tasks_unschedule(hal_task_t* task)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_tasks_unschedule);
  cmock_call_instance = (CMOCK_hal_tasks_unschedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_tasks_unschedule_CallInstance);
  Mock.hal_tasks_unschedule_CallInstance = CMock_Guts_MemNext(Mock.hal_tasks_unschedule_CallInstance);
  if (Mock.hal_tasks_unschedule_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_tasks_unschedule_CallbackBool &&
      Mock.hal_tasks_unschedule_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_unschedule_CallbackFunctionPointer(task, Mock.hal_tasks_unschedule_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_tasks_unschedule,CMockString_task);
    if (cmock_call_instance->Expected_task == NULL)
      { UNITY_TEST_ASSERT_NULL(task, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_task), (void*)(task), sizeof(hal_task_t), cmock_call_instance->Expected_task_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.hal_tasks_unschedule_CallbackFunctionPointer != NULL)
  {
    Mock.hal_tasks_unschedule_CallbackFunctionPointer(task, Mock.hal_tasks_unschedule_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_tasks_unschedule(CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth);
void CMockExpectParameters_hal_tasks_unschedule(CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance, hal_task_t* task, int task_Depth)
{
  cmock_call_instance->Expected_task = task;
  cmock_call_instance->Expected_task_Depth = task_Depth;
}

void hal_tasks_unschedule_CMockIgnore(void)
{
  Mock.hal_tasks_unschedule_IgnoreBool = (char)1;
}

void hal_tasks_unschedule_CMockStopIgnore(void)
{
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
}

void hal_tasks_unschedule_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_unschedule_CALL_INSTANCE));
  CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_unschedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_unschedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_unschedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_tasks_unschedule_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_unschedule_CALL_INSTANCE));
  CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_unschedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_unschedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_unschedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_unschedule(cmock_call_instance, task, 1);
}

void hal_tasks_unschedule_AddCallback(CMOCK_hal_tasks_unschedule_CALLBACK Callback)
{
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
  Mock.hal_tasks_unschedule_CallbackBool = (char)1;
  Mock.hal_tasks_unschedule_CallbackFunctionPointer = Callback;
}

void hal_tasks_unschedule_Stub(CMOCK_hal_tasks_unschedule_CALLBACK Callback)
{
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
  Mock.hal_tasks_unschedule_CallbackBool = (char)0;
  Mock.hal_tasks_unschedule_CallbackFunctionPointer = Callback;
}

void hal_tasks_unschedule_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_tasks_unschedule_CALL_INSTANCE));
  CMOCK_hal_tasks_unschedule_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_tasks_unschedule_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_tasks_unschedule_CallInstance = CMock_Guts_MemChain(Mock.hal_tasks_unschedule_CallInstance, cmock_guts_index);
  Mock.hal_tasks_unschedule_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_tasks_unschedule(cmock_call_instance, task, task_Depth);
}

