/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocktimer.h"

static const char* CMockString_hal_millis = "hal_millis";

typedef struct _CMOCK_hal_millis_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_hal_millis_CALL_INSTANCE;

static struct MocktimerInstance
{
  char hal_millis_IgnoreBool;
  uint32_t hal_millis_FinalReturn;
  char hal_millis_CallbackBool;
  CMOCK_hal_millis_CALLBACK hal_millis_CallbackFunctionPointer;
  int hal_millis_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_millis_CallInstance;
} Mock;


void Mocktimer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.hal_millis_CallInstance;
  if (Mock.hal_millis_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_millis);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_millis_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mocktimer_Init(void)
{
  Mocktimer_Destroy();
}

void Mocktimer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint32_t hal_millis(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_millis_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_millis);
  cmock_call_instance = (CMOCK_hal_millis_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_millis_CallInstance);
  Mock.hal_millis_CallInstance = CMock_Guts_MemNext(Mock.hal_millis_CallInstance);
  if (Mock.hal_millis_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_millis_FinalReturn;
    Mock.hal_millis_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_millis_CallbackBool &&
      Mock.hal_millis_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.hal_millis_CallbackFunctionPointer(Mock.hal_millis_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_millis_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_millis_CallbackFunctionPointer(Mock.hal_millis_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void hal_millis_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_millis_CALL_INSTANCE));
  CMOCK_hal_millis_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_millis_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_millis_CallInstance = CMock_Guts_MemChain(Mock.hal_millis_CallInstance, cmock_guts_index);
  Mock.hal_millis_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_millis_IgnoreBool = (char)1;
}

void hal_millis_CMockStopIgnore(void)
{
  if(Mock.hal_millis_IgnoreBool)
    Mock.hal_millis_CallInstance = CMock_Guts_MemNext(Mock.hal_millis_CallInstance);
  Mock.hal_millis_IgnoreBool = (char)0;
}

void hal_millis_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_millis_CALL_INSTANCE));
  CMOCK_hal_millis_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_millis_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_millis_CallInstance = CMock_Guts_MemChain(Mock.hal_millis_CallInstance, cmock_guts_index);
  Mock.hal_millis_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void hal_millis_AddCallback(CMOCK_hal_millis_CALLBACK Callback)
{
  Mock.hal_millis_IgnoreBool = (char)0;
  Mock.hal_millis_CallbackBool = (char)1;
  Mock.hal_millis_CallbackFunctionPointer = Callback;
}

void hal_millis_Stub(CMOCK_hal_millis_CALLBACK Callback)
{
  Mock.hal_millis_IgnoreBool = (char)0;
  Mock.hal_millis_CallbackBool = (char)0;
  Mock.hal_millis_CallbackFunctionPointer = Callback;
}

