/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockstep_command_handler.h"

static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_cmock_arg2 = "cmock_arg2";
static const char* CMockString_cmock_arg3 = "cmock_arg3";
static const char* CMockString_new_step_command_handler = "new_step_command_handler";
static const char* CMockString_step_command_handler_register_callback = "step_command_handler_register_callback";
static const char* CMockString_step_command_handler_step_down = "step_command_handler_step_down";
static const char* CMockString_step_command_handler_step_up = "step_command_handler_step_up";

typedef struct _CMOCK_new_step_command_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  step_command_handler_t* Expected_cmock_arg1;
  int Expected_cmock_arg1_Depth;

} CMOCK_new_step_command_handler_CALL_INSTANCE;

typedef struct _CMOCK_step_command_handler_register_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  step_command_handler_t* Expected_cmock_arg1;
  step_command_handler_callback_t Expected_cmock_arg2;
  void* Expected_cmock_arg3;
  int Expected_cmock_arg1_Depth;
  int Expected_cmock_arg3_Depth;

} CMOCK_step_command_handler_register_callback_CALL_INSTANCE;

typedef struct _CMOCK_step_command_handler_step_up_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  step_command_handler_t* Expected_cmock_arg1;
  int Expected_cmock_arg1_Depth;

} CMOCK_step_command_handler_step_up_CALL_INSTANCE;

typedef struct _CMOCK_step_command_handler_step_down_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  step_command_handler_t* Expected_cmock_arg1;
  int Expected_cmock_arg1_Depth;

} CMOCK_step_command_handler_step_down_CALL_INSTANCE;

static struct Mockstep_command_handlerInstance
{
  char new_step_command_handler_IgnoreBool;
  char new_step_command_handler_CallbackBool;
  CMOCK_new_step_command_handler_CALLBACK new_step_command_handler_CallbackFunctionPointer;
  int new_step_command_handler_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE new_step_command_handler_CallInstance;
  char step_command_handler_register_callback_IgnoreBool;
  char step_command_handler_register_callback_CallbackBool;
  CMOCK_step_command_handler_register_callback_CALLBACK step_command_handler_register_callback_CallbackFunctionPointer;
  int step_command_handler_register_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE step_command_handler_register_callback_CallInstance;
  char step_command_handler_step_up_IgnoreBool;
  char step_command_handler_step_up_CallbackBool;
  CMOCK_step_command_handler_step_up_CALLBACK step_command_handler_step_up_CallbackFunctionPointer;
  int step_command_handler_step_up_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE step_command_handler_step_up_CallInstance;
  char step_command_handler_step_down_IgnoreBool;
  char step_command_handler_step_down_CallbackBool;
  CMOCK_step_command_handler_step_down_CALLBACK step_command_handler_step_down_CallbackFunctionPointer;
  int step_command_handler_step_down_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE step_command_handler_step_down_CallInstance;
} Mock;


void Mockstep_command_handler_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.new_step_command_handler_CallInstance;
  if (Mock.new_step_command_handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_new_step_command_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.new_step_command_handler_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.step_command_handler_register_callback_CallInstance;
  if (Mock.step_command_handler_register_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_step_command_handler_register_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.step_command_handler_register_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.step_command_handler_step_up_CallInstance;
  if (Mock.step_command_handler_step_up_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_step_command_handler_step_up);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.step_command_handler_step_up_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.step_command_handler_step_down_CallInstance;
  if (Mock.step_command_handler_step_down_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_step_command_handler_step_down);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.step_command_handler_step_down_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockstep_command_handler_Init(void)
{
  Mockstep_command_handler_Destroy();
}

void Mockstep_command_handler_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void new_step_command_handler(step_command_handler_t* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_new_step_command_handler);
  cmock_call_instance = (CMOCK_new_step_command_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.new_step_command_handler_CallInstance);
  Mock.new_step_command_handler_CallInstance = CMock_Guts_MemNext(Mock.new_step_command_handler_CallInstance);
  if (Mock.new_step_command_handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.new_step_command_handler_CallbackBool &&
      Mock.new_step_command_handler_CallbackFunctionPointer != NULL)
  {
    Mock.new_step_command_handler_CallbackFunctionPointer(cmock_arg1, Mock.new_step_command_handler_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_new_step_command_handler,CMockString_cmock_arg1);
    if (cmock_call_instance->Expected_cmock_arg1 == NULL)
      { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(step_command_handler_t), cmock_call_instance->Expected_cmock_arg1_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.new_step_command_handler_CallbackFunctionPointer != NULL)
  {
    Mock.new_step_command_handler_CallbackFunctionPointer(cmock_arg1, Mock.new_step_command_handler_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_new_step_command_handler(CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);
void CMockExpectParameters_new_step_command_handler(CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg1_Depth = cmock_arg1_Depth;
}

void new_step_command_handler_CMockIgnore(void)
{
  Mock.new_step_command_handler_IgnoreBool = (char)1;
}

void new_step_command_handler_CMockStopIgnore(void)
{
  Mock.new_step_command_handler_IgnoreBool = (char)0;
}

void new_step_command_handler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_new_step_command_handler_CALL_INSTANCE));
  CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_new_step_command_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.new_step_command_handler_CallInstance = CMock_Guts_MemChain(Mock.new_step_command_handler_CallInstance, cmock_guts_index);
  Mock.new_step_command_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void new_step_command_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_new_step_command_handler_CALL_INSTANCE));
  CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_new_step_command_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.new_step_command_handler_CallInstance = CMock_Guts_MemChain(Mock.new_step_command_handler_CallInstance, cmock_guts_index);
  Mock.new_step_command_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_new_step_command_handler(cmock_call_instance, cmock_arg1, 1);
}

void new_step_command_handler_AddCallback(CMOCK_new_step_command_handler_CALLBACK Callback)
{
  Mock.new_step_command_handler_IgnoreBool = (char)0;
  Mock.new_step_command_handler_CallbackBool = (char)1;
  Mock.new_step_command_handler_CallbackFunctionPointer = Callback;
}

void new_step_command_handler_Stub(CMOCK_new_step_command_handler_CALLBACK Callback)
{
  Mock.new_step_command_handler_IgnoreBool = (char)0;
  Mock.new_step_command_handler_CallbackBool = (char)0;
  Mock.new_step_command_handler_CallbackFunctionPointer = Callback;
}

void new_step_command_handler_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_new_step_command_handler_CALL_INSTANCE));
  CMOCK_new_step_command_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_new_step_command_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.new_step_command_handler_CallInstance = CMock_Guts_MemChain(Mock.new_step_command_handler_CallInstance, cmock_guts_index);
  Mock.new_step_command_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_new_step_command_handler(cmock_call_instance, cmock_arg1, cmock_arg1_Depth);
}

void step_command_handler_register_callback(step_command_handler_t* cmock_arg1, step_command_handler_callback_t cmock_arg2, void* cmock_arg3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_step_command_handler_register_callback);
  cmock_call_instance = (CMOCK_step_command_handler_register_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.step_command_handler_register_callback_CallInstance);
  Mock.step_command_handler_register_callback_CallInstance = CMock_Guts_MemNext(Mock.step_command_handler_register_callback_CallInstance);
  if (Mock.step_command_handler_register_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.step_command_handler_register_callback_CallbackBool &&
      Mock.step_command_handler_register_callback_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_register_callback_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, Mock.step_command_handler_register_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_step_command_handler_register_callback,CMockString_cmock_arg1);
    if (cmock_call_instance->Expected_cmock_arg1 == NULL)
      { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(step_command_handler_t), cmock_call_instance->Expected_cmock_arg1_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_step_command_handler_register_callback,CMockString_cmock_arg2);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg2), (void*)(&cmock_arg2), sizeof(step_command_handler_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_step_command_handler_register_callback,CMockString_cmock_arg3);
    if (cmock_call_instance->Expected_cmock_arg3 == NULL)
      { UNITY_TEST_ASSERT_NULL(cmock_arg3, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_cmock_arg3, cmock_arg3, cmock_call_instance->Expected_cmock_arg3_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.step_command_handler_register_callback_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_register_callback_CallbackFunctionPointer(cmock_arg1, cmock_arg2, cmock_arg3, Mock.step_command_handler_register_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_step_command_handler_register_callback(CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth, step_command_handler_callback_t cmock_arg2, void* cmock_arg3, int cmock_arg3_Depth);
void CMockExpectParameters_step_command_handler_register_callback(CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth, step_command_handler_callback_t cmock_arg2, void* cmock_arg3, int cmock_arg3_Depth)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg1_Depth = cmock_arg1_Depth;
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg2), (void*)(&cmock_arg2),
         sizeof(step_command_handler_callback_t[sizeof(cmock_arg2) == sizeof(step_command_handler_callback_t) ? 1 : -1])); /* add step_command_handler_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_cmock_arg3 = cmock_arg3;
  cmock_call_instance->Expected_cmock_arg3_Depth = cmock_arg3_Depth;
}

void step_command_handler_register_callback_CMockIgnore(void)
{
  Mock.step_command_handler_register_callback_IgnoreBool = (char)1;
}

void step_command_handler_register_callback_CMockStopIgnore(void)
{
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
}

void step_command_handler_register_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_register_callback_CALL_INSTANCE));
  CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_register_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_register_callback_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_register_callback_CallInstance, cmock_guts_index);
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void step_command_handler_register_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, step_command_handler_callback_t cmock_arg2, void* cmock_arg3)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_register_callback_CALL_INSTANCE));
  CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_register_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_register_callback_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_register_callback_CallInstance, cmock_guts_index);
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_register_callback(cmock_call_instance, cmock_arg1, 1, cmock_arg2, cmock_arg3, 1);
}

void step_command_handler_register_callback_AddCallback(CMOCK_step_command_handler_register_callback_CALLBACK Callback)
{
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
  Mock.step_command_handler_register_callback_CallbackBool = (char)1;
  Mock.step_command_handler_register_callback_CallbackFunctionPointer = Callback;
}

void step_command_handler_register_callback_Stub(CMOCK_step_command_handler_register_callback_CALLBACK Callback)
{
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
  Mock.step_command_handler_register_callback_CallbackBool = (char)0;
  Mock.step_command_handler_register_callback_CallbackFunctionPointer = Callback;
}

void step_command_handler_register_callback_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth, step_command_handler_callback_t cmock_arg2, void* cmock_arg3, int cmock_arg3_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_register_callback_CALL_INSTANCE));
  CMOCK_step_command_handler_register_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_register_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_register_callback_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_register_callback_CallInstance, cmock_guts_index);
  Mock.step_command_handler_register_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_register_callback(cmock_call_instance, cmock_arg1, cmock_arg1_Depth, cmock_arg2, cmock_arg3, cmock_arg3_Depth);
}

void step_command_handler_step_up(step_command_handler_t* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_step_command_handler_step_up);
  cmock_call_instance = (CMOCK_step_command_handler_step_up_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.step_command_handler_step_up_CallInstance);
  Mock.step_command_handler_step_up_CallInstance = CMock_Guts_MemNext(Mock.step_command_handler_step_up_CallInstance);
  if (Mock.step_command_handler_step_up_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.step_command_handler_step_up_CallbackBool &&
      Mock.step_command_handler_step_up_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_step_up_CallbackFunctionPointer(cmock_arg1, Mock.step_command_handler_step_up_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_step_command_handler_step_up,CMockString_cmock_arg1);
    if (cmock_call_instance->Expected_cmock_arg1 == NULL)
      { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(step_command_handler_t), cmock_call_instance->Expected_cmock_arg1_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.step_command_handler_step_up_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_step_up_CallbackFunctionPointer(cmock_arg1, Mock.step_command_handler_step_up_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_step_command_handler_step_up(CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);
void CMockExpectParameters_step_command_handler_step_up(CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg1_Depth = cmock_arg1_Depth;
}

void step_command_handler_step_up_CMockIgnore(void)
{
  Mock.step_command_handler_step_up_IgnoreBool = (char)1;
}

void step_command_handler_step_up_CMockStopIgnore(void)
{
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
}

void step_command_handler_step_up_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_up_CALL_INSTANCE));
  CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_up_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_up_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_up_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void step_command_handler_step_up_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_up_CALL_INSTANCE));
  CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_up_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_up_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_up_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_step_up(cmock_call_instance, cmock_arg1, 1);
}

void step_command_handler_step_up_AddCallback(CMOCK_step_command_handler_step_up_CALLBACK Callback)
{
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
  Mock.step_command_handler_step_up_CallbackBool = (char)1;
  Mock.step_command_handler_step_up_CallbackFunctionPointer = Callback;
}

void step_command_handler_step_up_Stub(CMOCK_step_command_handler_step_up_CALLBACK Callback)
{
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
  Mock.step_command_handler_step_up_CallbackBool = (char)0;
  Mock.step_command_handler_step_up_CallbackFunctionPointer = Callback;
}

void step_command_handler_step_up_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_up_CALL_INSTANCE));
  CMOCK_step_command_handler_step_up_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_up_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_up_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_up_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_up_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_step_up(cmock_call_instance, cmock_arg1, cmock_arg1_Depth);
}

void step_command_handler_step_down(step_command_handler_t* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_step_command_handler_step_down);
  cmock_call_instance = (CMOCK_step_command_handler_step_down_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.step_command_handler_step_down_CallInstance);
  Mock.step_command_handler_step_down_CallInstance = CMock_Guts_MemNext(Mock.step_command_handler_step_down_CallInstance);
  if (Mock.step_command_handler_step_down_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.step_command_handler_step_down_CallbackBool &&
      Mock.step_command_handler_step_down_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_step_down_CallbackFunctionPointer(cmock_arg1, Mock.step_command_handler_step_down_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_step_command_handler_step_down,CMockString_cmock_arg1);
    if (cmock_call_instance->Expected_cmock_arg1 == NULL)
      { UNITY_TEST_ASSERT_NULL(cmock_arg1, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(step_command_handler_t), cmock_call_instance->Expected_cmock_arg1_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.step_command_handler_step_down_CallbackFunctionPointer != NULL)
  {
    Mock.step_command_handler_step_down_CallbackFunctionPointer(cmock_arg1, Mock.step_command_handler_step_down_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_step_command_handler_step_down(CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);
void CMockExpectParameters_step_command_handler_step_down(CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
  cmock_call_instance->Expected_cmock_arg1_Depth = cmock_arg1_Depth;
}

void step_command_handler_step_down_CMockIgnore(void)
{
  Mock.step_command_handler_step_down_IgnoreBool = (char)1;
}

void step_command_handler_step_down_CMockStopIgnore(void)
{
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
}

void step_command_handler_step_down_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_down_CALL_INSTANCE));
  CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_down_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_down_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_down_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void step_command_handler_step_down_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_down_CALL_INSTANCE));
  CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_down_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_down_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_down_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_step_down(cmock_call_instance, cmock_arg1, 1);
}

void step_command_handler_step_down_AddCallback(CMOCK_step_command_handler_step_down_CALLBACK Callback)
{
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
  Mock.step_command_handler_step_down_CallbackBool = (char)1;
  Mock.step_command_handler_step_down_CallbackFunctionPointer = Callback;
}

void step_command_handler_step_down_Stub(CMOCK_step_command_handler_step_down_CALLBACK Callback)
{
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
  Mock.step_command_handler_step_down_CallbackBool = (char)0;
  Mock.step_command_handler_step_down_CallbackFunctionPointer = Callback;
}

void step_command_handler_step_down_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_step_command_handler_step_down_CALL_INSTANCE));
  CMOCK_step_command_handler_step_down_CALL_INSTANCE* cmock_call_instance = (CMOCK_step_command_handler_step_down_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.step_command_handler_step_down_CallInstance = CMock_Guts_MemChain(Mock.step_command_handler_step_down_CallInstance, cmock_guts_index);
  Mock.step_command_handler_step_down_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_step_command_handler_step_down(cmock_call_instance, cmock_arg1, cmock_arg1_Depth);
}

