/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTEP_COMMAND_HANDLER_H
#define _MOCKSTEP_COMMAND_HANDLER_H

#include "unity.h"
#include "step_command_handler.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockstep_command_handler_Init(void);
void Mockstep_command_handler_Destroy(void);
void Mockstep_command_handler_Verify(void);




#define new_step_command_handler_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("new_step_command_handler requires _Ignore (not AndReturn)");
#define new_step_command_handler_Ignore() new_step_command_handler_CMockIgnore()
void new_step_command_handler_CMockIgnore(void);
#define new_step_command_handler_StopIgnore() new_step_command_handler_CMockStopIgnore()
void new_step_command_handler_CMockStopIgnore(void);
#define new_step_command_handler_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("new_step_command_handler requires _ExpectAnyArgs (not AndReturn)");
#define new_step_command_handler_ExpectAnyArgs() new_step_command_handler_CMockExpectAnyArgs(__LINE__)
void new_step_command_handler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define new_step_command_handler_ExpectAndReturn(cmock_arg1, cmock_retval) TEST_FAIL_MESSAGE("new_step_command_handler requires _Expect (not AndReturn)");
#define new_step_command_handler_Expect(cmock_arg1) new_step_command_handler_CMockExpect(__LINE__, cmock_arg1)
void new_step_command_handler_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1);
typedef void (* CMOCK_new_step_command_handler_CALLBACK)(step_command_handler_t* cmock_arg1, int cmock_num_calls);
void new_step_command_handler_AddCallback(CMOCK_new_step_command_handler_CALLBACK Callback);
void new_step_command_handler_Stub(CMOCK_new_step_command_handler_CALLBACK Callback);
#define new_step_command_handler_StubWithCallback new_step_command_handler_Stub
#define new_step_command_handler_ExpectWithArrayAndReturn(cmock_arg1, cmock_arg1_Depth, cmock_retval) TEST_FAIL_MESSAGE("new_step_command_handler requires _ExpectWithArray (not AndReturn)");
#define new_step_command_handler_ExpectWithArray(cmock_arg1, cmock_arg1_Depth) new_step_command_handler_CMockExpectWithArray(__LINE__, cmock_arg1, (cmock_arg1_Depth))
void new_step_command_handler_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);
#define step_command_handler_register_callback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_register_callback requires _Ignore (not AndReturn)");
#define step_command_handler_register_callback_Ignore() step_command_handler_register_callback_CMockIgnore()
void step_command_handler_register_callback_CMockIgnore(void);
#define step_command_handler_register_callback_StopIgnore() step_command_handler_register_callback_CMockStopIgnore()
void step_command_handler_register_callback_CMockStopIgnore(void);
#define step_command_handler_register_callback_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_register_callback requires _ExpectAnyArgs (not AndReturn)");
#define step_command_handler_register_callback_ExpectAnyArgs() step_command_handler_register_callback_CMockExpectAnyArgs(__LINE__)
void step_command_handler_register_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define step_command_handler_register_callback_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_arg3, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_register_callback requires _Expect (not AndReturn)");
#define step_command_handler_register_callback_Expect(cmock_arg1, cmock_arg2, cmock_arg3) step_command_handler_register_callback_CMockExpect(__LINE__, cmock_arg1, cmock_arg2, cmock_arg3)
void step_command_handler_register_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, step_command_handler_callback_t cmock_arg2, void* cmock_arg3);
typedef void (* CMOCK_step_command_handler_register_callback_CALLBACK)(step_command_handler_t* cmock_arg1, step_command_handler_callback_t cmock_arg2, void* cmock_arg3, int cmock_num_calls);
void step_command_handler_register_callback_AddCallback(CMOCK_step_command_handler_register_callback_CALLBACK Callback);
void step_command_handler_register_callback_Stub(CMOCK_step_command_handler_register_callback_CALLBACK Callback);
#define step_command_handler_register_callback_StubWithCallback step_command_handler_register_callback_Stub
#define step_command_handler_register_callback_ExpectWithArrayAndReturn(cmock_arg1, cmock_arg1_Depth, cmock_arg2, cmock_arg3, cmock_arg3_Depth, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_register_callback requires _ExpectWithArray (not AndReturn)");
#define step_command_handler_register_callback_ExpectWithArray(cmock_arg1, cmock_arg1_Depth, cmock_arg2, cmock_arg3, cmock_arg3_Depth) step_command_handler_register_callback_CMockExpectWithArray(__LINE__, cmock_arg1, (cmock_arg1_Depth), cmock_arg2, cmock_arg3, (cmock_arg3_Depth))
void step_command_handler_register_callback_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth, step_command_handler_callback_t cmock_arg2, void* cmock_arg3, int cmock_arg3_Depth);
#define step_command_handler_step_up_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_up requires _Ignore (not AndReturn)");
#define step_command_handler_step_up_Ignore() step_command_handler_step_up_CMockIgnore()
void step_command_handler_step_up_CMockIgnore(void);
#define step_command_handler_step_up_StopIgnore() step_command_handler_step_up_CMockStopIgnore()
void step_command_handler_step_up_CMockStopIgnore(void);
#define step_command_handler_step_up_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_up requires _ExpectAnyArgs (not AndReturn)");
#define step_command_handler_step_up_ExpectAnyArgs() step_command_handler_step_up_CMockExpectAnyArgs(__LINE__)
void step_command_handler_step_up_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define step_command_handler_step_up_ExpectAndReturn(cmock_arg1, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_up requires _Expect (not AndReturn)");
#define step_command_handler_step_up_Expect(cmock_arg1) step_command_handler_step_up_CMockExpect(__LINE__, cmock_arg1)
void step_command_handler_step_up_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1);
typedef void (* CMOCK_step_command_handler_step_up_CALLBACK)(step_command_handler_t* cmock_arg1, int cmock_num_calls);
void step_command_handler_step_up_AddCallback(CMOCK_step_command_handler_step_up_CALLBACK Callback);
void step_command_handler_step_up_Stub(CMOCK_step_command_handler_step_up_CALLBACK Callback);
#define step_command_handler_step_up_StubWithCallback step_command_handler_step_up_Stub
#define step_command_handler_step_up_ExpectWithArrayAndReturn(cmock_arg1, cmock_arg1_Depth, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_up requires _ExpectWithArray (not AndReturn)");
#define step_command_handler_step_up_ExpectWithArray(cmock_arg1, cmock_arg1_Depth) step_command_handler_step_up_CMockExpectWithArray(__LINE__, cmock_arg1, (cmock_arg1_Depth))
void step_command_handler_step_up_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);
#define step_command_handler_step_down_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_down requires _Ignore (not AndReturn)");
#define step_command_handler_step_down_Ignore() step_command_handler_step_down_CMockIgnore()
void step_command_handler_step_down_CMockIgnore(void);
#define step_command_handler_step_down_StopIgnore() step_command_handler_step_down_CMockStopIgnore()
void step_command_handler_step_down_CMockStopIgnore(void);
#define step_command_handler_step_down_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_down requires _ExpectAnyArgs (not AndReturn)");
#define step_command_handler_step_down_ExpectAnyArgs() step_command_handler_step_down_CMockExpectAnyArgs(__LINE__)
void step_command_handler_step_down_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define step_command_handler_step_down_ExpectAndReturn(cmock_arg1, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_down requires _Expect (not AndReturn)");
#define step_command_handler_step_down_Expect(cmock_arg1) step_command_handler_step_down_CMockExpect(__LINE__, cmock_arg1)
void step_command_handler_step_down_CMockExpect(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1);
typedef void (* CMOCK_step_command_handler_step_down_CALLBACK)(step_command_handler_t* cmock_arg1, int cmock_num_calls);
void step_command_handler_step_down_AddCallback(CMOCK_step_command_handler_step_down_CALLBACK Callback);
void step_command_handler_step_down_Stub(CMOCK_step_command_handler_step_down_CALLBACK Callback);
#define step_command_handler_step_down_StubWithCallback step_command_handler_step_down_Stub
#define step_command_handler_step_down_ExpectWithArrayAndReturn(cmock_arg1, cmock_arg1_Depth, cmock_retval) TEST_FAIL_MESSAGE("step_command_handler_step_down requires _ExpectWithArray (not AndReturn)");
#define step_command_handler_step_down_ExpectWithArray(cmock_arg1, cmock_arg1_Depth) step_command_handler_step_down_CMockExpectWithArray(__LINE__, cmock_arg1, (cmock_arg1_Depth))
void step_command_handler_step_down_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, step_command_handler_t* cmock_arg1, int cmock_arg1_Depth);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
