/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTASKS_H
#define _MOCKTASKS_H

#include "unity.h"
#include "tasks.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mocktasks_Init(void);
void Mocktasks_Destroy(void);
void Mocktasks_Verify(void);




#define hal_tasks_init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_init requires _Ignore (not AndReturn)");
#define hal_tasks_init_Ignore() hal_tasks_init_CMockIgnore()
void hal_tasks_init_CMockIgnore(void);
#define hal_tasks_init_StopIgnore() hal_tasks_init_CMockStopIgnore()
void hal_tasks_init_CMockStopIgnore(void);
#define hal_tasks_init_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_init requires _ExpectAnyArgs (not AndReturn)");
#define hal_tasks_init_ExpectAnyArgs() hal_tasks_init_CMockExpectAnyArgs(__LINE__)
void hal_tasks_init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define hal_tasks_init_ExpectAndReturn(task, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_init requires _Expect (not AndReturn)");
#define hal_tasks_init_Expect(task) hal_tasks_init_CMockExpect(__LINE__, task)
void hal_tasks_init_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task);
typedef void (* CMOCK_hal_tasks_init_CALLBACK)(hal_task_t* task, int cmock_num_calls);
void hal_tasks_init_AddCallback(CMOCK_hal_tasks_init_CALLBACK Callback);
void hal_tasks_init_Stub(CMOCK_hal_tasks_init_CALLBACK Callback);
#define hal_tasks_init_StubWithCallback hal_tasks_init_Stub
#define hal_tasks_init_ExpectWithArrayAndReturn(task, task_Depth, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_init requires _ExpectWithArray (not AndReturn)");
#define hal_tasks_init_ExpectWithArray(task, task_Depth) hal_tasks_init_CMockExpectWithArray(__LINE__, task, (task_Depth))
void hal_tasks_init_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth);
#define hal_tasks_schedule_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_schedule requires _Ignore (not AndReturn)");
#define hal_tasks_schedule_Ignore() hal_tasks_schedule_CMockIgnore()
void hal_tasks_schedule_CMockIgnore(void);
#define hal_tasks_schedule_StopIgnore() hal_tasks_schedule_CMockStopIgnore()
void hal_tasks_schedule_CMockStopIgnore(void);
#define hal_tasks_schedule_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_schedule requires _ExpectAnyArgs (not AndReturn)");
#define hal_tasks_schedule_ExpectAnyArgs() hal_tasks_schedule_CMockExpectAnyArgs(__LINE__)
void hal_tasks_schedule_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define hal_tasks_schedule_ExpectAndReturn(task, delay_ms, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_schedule requires _Expect (not AndReturn)");
#define hal_tasks_schedule_Expect(task, delay_ms) hal_tasks_schedule_CMockExpect(__LINE__, task, delay_ms)
void hal_tasks_schedule_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task, uint32_t delay_ms);
typedef void (* CMOCK_hal_tasks_schedule_CALLBACK)(hal_task_t* task, uint32_t delay_ms, int cmock_num_calls);
void hal_tasks_schedule_AddCallback(CMOCK_hal_tasks_schedule_CALLBACK Callback);
void hal_tasks_schedule_Stub(CMOCK_hal_tasks_schedule_CALLBACK Callback);
#define hal_tasks_schedule_StubWithCallback hal_tasks_schedule_Stub
#define hal_tasks_schedule_ExpectWithArrayAndReturn(task, task_Depth, delay_ms, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_schedule requires _ExpectWithArray (not AndReturn)");
#define hal_tasks_schedule_ExpectWithArray(task, task_Depth, delay_ms) hal_tasks_schedule_CMockExpectWithArray(__LINE__, task, (task_Depth), delay_ms)
void hal_tasks_schedule_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth, uint32_t delay_ms);
#define hal_tasks_unschedule_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_unschedule requires _Ignore (not AndReturn)");
#define hal_tasks_unschedule_Ignore() hal_tasks_unschedule_CMockIgnore()
void hal_tasks_unschedule_CMockIgnore(void);
#define hal_tasks_unschedule_StopIgnore() hal_tasks_unschedule_CMockStopIgnore()
void hal_tasks_unschedule_CMockStopIgnore(void);
#define hal_tasks_unschedule_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_unschedule requires _ExpectAnyArgs (not AndReturn)");
#define hal_tasks_unschedule_ExpectAnyArgs() hal_tasks_unschedule_CMockExpectAnyArgs(__LINE__)
void hal_tasks_unschedule_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define hal_tasks_unschedule_ExpectAndReturn(task, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_unschedule requires _Expect (not AndReturn)");
#define hal_tasks_unschedule_Expect(task) hal_tasks_unschedule_CMockExpect(__LINE__, task)
void hal_tasks_unschedule_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_task_t* task);
typedef void (* CMOCK_hal_tasks_unschedule_CALLBACK)(hal_task_t* task, int cmock_num_calls);
void hal_tasks_unschedule_AddCallback(CMOCK_hal_tasks_unschedule_CALLBACK Callback);
void hal_tasks_unschedule_Stub(CMOCK_hal_tasks_unschedule_CALLBACK Callback);
#define hal_tasks_unschedule_StubWithCallback hal_tasks_unschedule_Stub
#define hal_tasks_unschedule_ExpectWithArrayAndReturn(task, task_Depth, cmock_retval) TEST_FAIL_MESSAGE("hal_tasks_unschedule requires _ExpectWithArray (not AndReturn)");
#define hal_tasks_unschedule_ExpectWithArray(task, task_Depth) hal_tasks_unschedule_CMockExpectWithArray(__LINE__, task, (task_Depth))
void hal_tasks_unschedule_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_task_t* task, int task_Depth);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
