/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockzigbee.h"

static const char* CMockString_attr_id = "attr_id";
static const char* CMockString_attribute_id = "attribute_id";
static const char* CMockString_callback = "callback";
static const char* CMockString_cluster_id = "cluster_id";
static const char* CMockString_cmd = "cmd";
static const char* CMockString_endpoint = "endpoint";
static const char* CMockString_endpoints = "endpoints";
static const char* CMockString_endpoints_cnt = "endpoints_cnt";
static const char* CMockString_hal_register_on_network_status_change_callback = "hal_register_on_network_status_change_callback";
static const char* CMockString_hal_zigbee_get_network_status = "hal_zigbee_get_network_status";
static const char* CMockString_hal_zigbee_get_poll_rate_ms = "hal_zigbee_get_poll_rate_ms";
static const char* CMockString_hal_zigbee_init = "hal_zigbee_init";
static const char* CMockString_hal_zigbee_leave_network = "hal_zigbee_leave_network";
static const char* CMockString_hal_zigbee_notify_attribute_changed = "hal_zigbee_notify_attribute_changed";
static const char* CMockString_hal_zigbee_register_on_attribute_change_callback = "hal_zigbee_register_on_attribute_change_callback";
static const char* CMockString_hal_zigbee_register_on_zcl_activity_callback = "hal_zigbee_register_on_zcl_activity_callback";
static const char* CMockString_hal_zigbee_send_announce = "hal_zigbee_send_announce";
static const char* CMockString_hal_zigbee_send_cmd_to_bindings = "hal_zigbee_send_cmd_to_bindings";
static const char* CMockString_hal_zigbee_send_report_attr = "hal_zigbee_send_report_attr";
static const char* CMockString_hal_zigbee_set_image_type = "hal_zigbee_set_image_type";
static const char* CMockString_hal_zigbee_set_poll_rate_ms = "hal_zigbee_set_poll_rate_ms";
static const char* CMockString_hal_zigbee_start_network_steering = "hal_zigbee_start_network_steering";
static const char* CMockString_image_type = "image_type";
static const char* CMockString_poll_rate_ms = "poll_rate_ms";
static const char* CMockString_value = "value";
static const char* CMockString_value_len = "value_len";
static const char* CMockString_zcl_type_id = "zcl_type_id";

typedef struct _CMOCK_hal_zigbee_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zigbee_endpoint* Expected_endpoints;
  uint8_t Expected_endpoints_cnt;
  int Expected_endpoints_Depth;

} CMOCK_hal_zigbee_init_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zigbee_network_status_t ReturnVal;

} CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE;

typedef struct _CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_network_status_change_callback_t Expected_callback;

} CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_leave_network_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_hal_zigbee_leave_network_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint16_t Expected_image_type;

} CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint8_t Expected_endpoint;
  uint16_t Expected_cluster_id;
  uint16_t Expected_attribute_id;

} CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_attribute_change_callback_t Expected_callback;

} CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zigbee_status_t ReturnVal;
  const hal_zigbee_cmd* Expected_cmd;
  int Expected_cmd_Depth;

} CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zigbee_status_t ReturnVal;
  uint8_t Expected_endpoint;
  uint16_t Expected_cluster_id;
  uint16_t Expected_attr_id;
  uint8_t Expected_zcl_type_id;
  const void* Expected_value;
  uint8_t Expected_value_len;
  int Expected_value_Depth;

} CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_send_announce_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zigbee_status_t ReturnVal;

} CMOCK_hal_zigbee_send_announce_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  hal_zcl_activity_callback_t Expected_callback;

} CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t Expected_poll_rate_ms;

} CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE;

typedef struct _CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;

} CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE;

static struct MockzigbeeInstance
{
  char hal_zigbee_init_IgnoreBool;
  char hal_zigbee_init_CallbackBool;
  CMOCK_hal_zigbee_init_CALLBACK hal_zigbee_init_CallbackFunctionPointer;
  int hal_zigbee_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_init_CallInstance;
  char hal_zigbee_get_network_status_IgnoreBool;
  hal_zigbee_network_status_t hal_zigbee_get_network_status_FinalReturn;
  char hal_zigbee_get_network_status_CallbackBool;
  CMOCK_hal_zigbee_get_network_status_CALLBACK hal_zigbee_get_network_status_CallbackFunctionPointer;
  int hal_zigbee_get_network_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_get_network_status_CallInstance;
  char hal_register_on_network_status_change_callback_IgnoreBool;
  char hal_register_on_network_status_change_callback_CallbackBool;
  CMOCK_hal_register_on_network_status_change_callback_CALLBACK hal_register_on_network_status_change_callback_CallbackFunctionPointer;
  int hal_register_on_network_status_change_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_register_on_network_status_change_callback_CallInstance;
  char hal_zigbee_leave_network_IgnoreBool;
  char hal_zigbee_leave_network_CallbackBool;
  CMOCK_hal_zigbee_leave_network_CALLBACK hal_zigbee_leave_network_CallbackFunctionPointer;
  int hal_zigbee_leave_network_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_leave_network_CallInstance;
  char hal_zigbee_start_network_steering_IgnoreBool;
  char hal_zigbee_start_network_steering_CallbackBool;
  CMOCK_hal_zigbee_start_network_steering_CALLBACK hal_zigbee_start_network_steering_CallbackFunctionPointer;
  int hal_zigbee_start_network_steering_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_start_network_steering_CallInstance;
  char hal_zigbee_set_image_type_IgnoreBool;
  char hal_zigbee_set_image_type_CallbackBool;
  CMOCK_hal_zigbee_set_image_type_CALLBACK hal_zigbee_set_image_type_CallbackFunctionPointer;
  int hal_zigbee_set_image_type_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_set_image_type_CallInstance;
  char hal_zigbee_notify_attribute_changed_IgnoreBool;
  char hal_zigbee_notify_attribute_changed_CallbackBool;
  CMOCK_hal_zigbee_notify_attribute_changed_CALLBACK hal_zigbee_notify_attribute_changed_CallbackFunctionPointer;
  int hal_zigbee_notify_attribute_changed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_notify_attribute_changed_CallInstance;
  char hal_zigbee_register_on_attribute_change_callback_IgnoreBool;
  char hal_zigbee_register_on_attribute_change_callback_CallbackBool;
  CMOCK_hal_zigbee_register_on_attribute_change_callback_CALLBACK hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer;
  int hal_zigbee_register_on_attribute_change_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_register_on_attribute_change_callback_CallInstance;
  char hal_zigbee_send_cmd_to_bindings_IgnoreBool;
  hal_zigbee_status_t hal_zigbee_send_cmd_to_bindings_FinalReturn;
  char hal_zigbee_send_cmd_to_bindings_CallbackBool;
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALLBACK hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer;
  int hal_zigbee_send_cmd_to_bindings_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_send_cmd_to_bindings_CallInstance;
  char hal_zigbee_send_report_attr_IgnoreBool;
  hal_zigbee_status_t hal_zigbee_send_report_attr_FinalReturn;
  char hal_zigbee_send_report_attr_CallbackBool;
  CMOCK_hal_zigbee_send_report_attr_CALLBACK hal_zigbee_send_report_attr_CallbackFunctionPointer;
  int hal_zigbee_send_report_attr_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_send_report_attr_CallInstance;
  char hal_zigbee_send_announce_IgnoreBool;
  hal_zigbee_status_t hal_zigbee_send_announce_FinalReturn;
  char hal_zigbee_send_announce_CallbackBool;
  CMOCK_hal_zigbee_send_announce_CALLBACK hal_zigbee_send_announce_CallbackFunctionPointer;
  int hal_zigbee_send_announce_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_send_announce_CallInstance;
  char hal_zigbee_register_on_zcl_activity_callback_IgnoreBool;
  char hal_zigbee_register_on_zcl_activity_callback_CallbackBool;
  CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALLBACK hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer;
  int hal_zigbee_register_on_zcl_activity_callback_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_register_on_zcl_activity_callback_CallInstance;
  char hal_zigbee_set_poll_rate_ms_IgnoreBool;
  char hal_zigbee_set_poll_rate_ms_CallbackBool;
  CMOCK_hal_zigbee_set_poll_rate_ms_CALLBACK hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer;
  int hal_zigbee_set_poll_rate_ms_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_set_poll_rate_ms_CallInstance;
  char hal_zigbee_get_poll_rate_ms_IgnoreBool;
  uint32_t hal_zigbee_get_poll_rate_ms_FinalReturn;
  char hal_zigbee_get_poll_rate_ms_CallbackBool;
  CMOCK_hal_zigbee_get_poll_rate_ms_CALLBACK hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer;
  int hal_zigbee_get_poll_rate_ms_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE hal_zigbee_get_poll_rate_ms_CallInstance;
} Mock;


void Mockzigbee_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.hal_zigbee_init_CallInstance;
  if (Mock.hal_zigbee_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_get_network_status_CallInstance;
  if (Mock.hal_zigbee_get_network_status_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_get_network_status);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_get_network_status_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_register_on_network_status_change_callback_CallInstance;
  if (Mock.hal_register_on_network_status_change_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_register_on_network_status_change_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_leave_network_CallInstance;
  if (Mock.hal_zigbee_leave_network_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_leave_network);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_leave_network_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_start_network_steering_CallInstance;
  if (Mock.hal_zigbee_start_network_steering_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_start_network_steering);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_set_image_type_CallInstance;
  if (Mock.hal_zigbee_set_image_type_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_set_image_type);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_set_image_type_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_notify_attribute_changed_CallInstance;
  if (Mock.hal_zigbee_notify_attribute_changed_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_notify_attribute_changed);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance;
  if (Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_register_on_attribute_change_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_send_cmd_to_bindings_CallInstance;
  if (Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_send_cmd_to_bindings);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_send_report_attr_CallInstance;
  if (Mock.hal_zigbee_send_report_attr_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_send_report_attr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_send_announce_CallInstance;
  if (Mock.hal_zigbee_send_announce_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_send_announce);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_send_announce_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance;
  if (Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_register_on_zcl_activity_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_set_poll_rate_ms_CallInstance;
  if (Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_set_poll_rate_ms);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.hal_zigbee_get_poll_rate_ms_CallInstance;
  if (Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_zigbee_get_poll_rate_ms);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockzigbee_Init(void)
{
  Mockzigbee_Destroy();
}

void Mockzigbee_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void hal_zigbee_init(hal_zigbee_endpoint* endpoints, uint8_t endpoints_cnt)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_init);
  cmock_call_instance = (CMOCK_hal_zigbee_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_init_CallInstance);
  Mock.hal_zigbee_init_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_init_CallInstance);
  if (Mock.hal_zigbee_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_init_CallbackBool &&
      Mock.hal_zigbee_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_init_CallbackFunctionPointer(endpoints, endpoints_cnt, Mock.hal_zigbee_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_init,CMockString_endpoints);
    if (cmock_call_instance->Expected_endpoints == NULL)
      { UNITY_TEST_ASSERT_NULL(endpoints, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_endpoints), (void*)(endpoints), sizeof(hal_zigbee_endpoint), cmock_call_instance->Expected_endpoints_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_init,CMockString_endpoints_cnt);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_endpoints_cnt, endpoints_cnt, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_init_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_init_CallbackFunctionPointer(endpoints, endpoints_cnt, Mock.hal_zigbee_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_init(CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance, hal_zigbee_endpoint* endpoints, int endpoints_Depth, uint8_t endpoints_cnt);
void CMockExpectParameters_hal_zigbee_init(CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance, hal_zigbee_endpoint* endpoints, int endpoints_Depth, uint8_t endpoints_cnt)
{
  cmock_call_instance->Expected_endpoints = endpoints;
  cmock_call_instance->Expected_endpoints_Depth = endpoints_Depth;
  cmock_call_instance->Expected_endpoints_cnt = endpoints_cnt;
}

void hal_zigbee_init_CMockIgnore(void)
{
  Mock.hal_zigbee_init_IgnoreBool = (char)1;
}

void hal_zigbee_init_CMockStopIgnore(void)
{
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
}

void hal_zigbee_init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_init_CALL_INSTANCE));
  CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_init_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_init_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_init_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_zigbee_endpoint* endpoints, uint8_t endpoints_cnt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_init_CALL_INSTANCE));
  CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_init_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_init_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_init(cmock_call_instance, endpoints, 1, endpoints_cnt);
}

void hal_zigbee_init_AddCallback(CMOCK_hal_zigbee_init_CALLBACK Callback)
{
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
  Mock.hal_zigbee_init_CallbackBool = (char)1;
  Mock.hal_zigbee_init_CallbackFunctionPointer = Callback;
}

void hal_zigbee_init_Stub(CMOCK_hal_zigbee_init_CALLBACK Callback)
{
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
  Mock.hal_zigbee_init_CallbackBool = (char)0;
  Mock.hal_zigbee_init_CallbackFunctionPointer = Callback;
}

void hal_zigbee_init_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, hal_zigbee_endpoint* endpoints, int endpoints_Depth, uint8_t endpoints_cnt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_init_CALL_INSTANCE));
  CMOCK_hal_zigbee_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_init_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_init_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_init(cmock_call_instance, endpoints, endpoints_Depth, endpoints_cnt);
}

hal_zigbee_network_status_t hal_zigbee_get_network_status(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_get_network_status);
  cmock_call_instance = (CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_get_network_status_CallInstance);
  Mock.hal_zigbee_get_network_status_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_get_network_status_CallInstance);
  if (Mock.hal_zigbee_get_network_status_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_zigbee_get_network_status_FinalReturn;
    memcpy((void*)(&Mock.hal_zigbee_get_network_status_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(hal_zigbee_network_status_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(hal_zigbee_network_status_t) ? 1 : -1])); /* add hal_zigbee_network_status_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_zigbee_get_network_status_CallbackBool &&
      Mock.hal_zigbee_get_network_status_CallbackFunctionPointer != NULL)
  {
    hal_zigbee_network_status_t cmock_cb_ret = Mock.hal_zigbee_get_network_status_CallbackFunctionPointer(Mock.hal_zigbee_get_network_status_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_zigbee_get_network_status_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_zigbee_get_network_status_CallbackFunctionPointer(Mock.hal_zigbee_get_network_status_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void hal_zigbee_get_network_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_network_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE));
  CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_get_network_status_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_get_network_status_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)1;
}

void hal_zigbee_get_network_status_CMockStopIgnore(void)
{
  if(Mock.hal_zigbee_get_network_status_IgnoreBool)
    Mock.hal_zigbee_get_network_status_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_get_network_status_CallInstance);
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)0;
}

void hal_zigbee_get_network_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_network_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE));
  CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_get_network_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_get_network_status_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_get_network_status_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_zigbee_network_status_t[sizeof(cmock_to_return) == sizeof(hal_zigbee_network_status_t) ? 1 : -1])); /* add hal_zigbee_network_status_t to :treat_as_array if this causes an error */
}

void hal_zigbee_get_network_status_AddCallback(CMOCK_hal_zigbee_get_network_status_CALLBACK Callback)
{
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)0;
  Mock.hal_zigbee_get_network_status_CallbackBool = (char)1;
  Mock.hal_zigbee_get_network_status_CallbackFunctionPointer = Callback;
}

void hal_zigbee_get_network_status_Stub(CMOCK_hal_zigbee_get_network_status_CALLBACK Callback)
{
  Mock.hal_zigbee_get_network_status_IgnoreBool = (char)0;
  Mock.hal_zigbee_get_network_status_CallbackBool = (char)0;
  Mock.hal_zigbee_get_network_status_CallbackFunctionPointer = Callback;
}

void hal_register_on_network_status_change_callback(hal_network_status_change_callback_t callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_register_on_network_status_change_callback);
  cmock_call_instance = (CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_register_on_network_status_change_callback_CallInstance);
  Mock.hal_register_on_network_status_change_callback_CallInstance = CMock_Guts_MemNext(Mock.hal_register_on_network_status_change_callback_CallInstance);
  if (Mock.hal_register_on_network_status_change_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_register_on_network_status_change_callback_CallbackBool &&
      Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer(callback, Mock.hal_register_on_network_status_change_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_register_on_network_status_change_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(hal_network_status_change_callback_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer(callback, Mock.hal_register_on_network_status_change_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_register_on_network_status_change_callback(CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE* cmock_call_instance, hal_network_status_change_callback_t callback);
void CMockExpectParameters_hal_register_on_network_status_change_callback(CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE* cmock_call_instance, hal_network_status_change_callback_t callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(hal_network_status_change_callback_t[sizeof(callback) == sizeof(hal_network_status_change_callback_t) ? 1 : -1])); /* add hal_network_status_change_callback_t to :treat_as_array if this causes an error */
}

void hal_register_on_network_status_change_callback_CMockIgnore(void)
{
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)1;
}

void hal_register_on_network_status_change_callback_CMockStopIgnore(void)
{
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)0;
}

void hal_register_on_network_status_change_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE));
  CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_register_on_network_status_change_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_register_on_network_status_change_callback_CallInstance, cmock_guts_index);
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_register_on_network_status_change_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_network_status_change_callback_t callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE));
  CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_register_on_network_status_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_register_on_network_status_change_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_register_on_network_status_change_callback_CallInstance, cmock_guts_index);
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_register_on_network_status_change_callback(cmock_call_instance, callback);
}

void hal_register_on_network_status_change_callback_AddCallback(CMOCK_hal_register_on_network_status_change_callback_CALLBACK Callback)
{
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)0;
  Mock.hal_register_on_network_status_change_callback_CallbackBool = (char)1;
  Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer = Callback;
}

void hal_register_on_network_status_change_callback_Stub(CMOCK_hal_register_on_network_status_change_callback_CALLBACK Callback)
{
  Mock.hal_register_on_network_status_change_callback_IgnoreBool = (char)0;
  Mock.hal_register_on_network_status_change_callback_CallbackBool = (char)0;
  Mock.hal_register_on_network_status_change_callback_CallbackFunctionPointer = Callback;
}

void hal_zigbee_leave_network(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_leave_network_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_leave_network);
  cmock_call_instance = (CMOCK_hal_zigbee_leave_network_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_leave_network_CallInstance);
  Mock.hal_zigbee_leave_network_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_leave_network_CallInstance);
  if (Mock.hal_zigbee_leave_network_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_leave_network_CallbackBool &&
      Mock.hal_zigbee_leave_network_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_leave_network_CallbackFunctionPointer(Mock.hal_zigbee_leave_network_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_zigbee_leave_network_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_leave_network_CallbackFunctionPointer(Mock.hal_zigbee_leave_network_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void hal_zigbee_leave_network_CMockIgnore(void)
{
  Mock.hal_zigbee_leave_network_IgnoreBool = (char)1;
}

void hal_zigbee_leave_network_CMockStopIgnore(void)
{
  Mock.hal_zigbee_leave_network_IgnoreBool = (char)0;
}

void hal_zigbee_leave_network_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_leave_network_CALL_INSTANCE));
  CMOCK_hal_zigbee_leave_network_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_leave_network_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_leave_network_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_leave_network_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_leave_network_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void hal_zigbee_leave_network_AddCallback(CMOCK_hal_zigbee_leave_network_CALLBACK Callback)
{
  Mock.hal_zigbee_leave_network_IgnoreBool = (char)0;
  Mock.hal_zigbee_leave_network_CallbackBool = (char)1;
  Mock.hal_zigbee_leave_network_CallbackFunctionPointer = Callback;
}

void hal_zigbee_leave_network_Stub(CMOCK_hal_zigbee_leave_network_CALLBACK Callback)
{
  Mock.hal_zigbee_leave_network_IgnoreBool = (char)0;
  Mock.hal_zigbee_leave_network_CallbackBool = (char)0;
  Mock.hal_zigbee_leave_network_CallbackFunctionPointer = Callback;
}

void hal_zigbee_start_network_steering(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_start_network_steering);
  cmock_call_instance = (CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_start_network_steering_CallInstance);
  Mock.hal_zigbee_start_network_steering_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_start_network_steering_CallInstance);
  if (Mock.hal_zigbee_start_network_steering_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_start_network_steering_CallbackBool &&
      Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer(Mock.hal_zigbee_start_network_steering_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer(Mock.hal_zigbee_start_network_steering_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void hal_zigbee_start_network_steering_CMockIgnore(void)
{
  Mock.hal_zigbee_start_network_steering_IgnoreBool = (char)1;
}

void hal_zigbee_start_network_steering_CMockStopIgnore(void)
{
  Mock.hal_zigbee_start_network_steering_IgnoreBool = (char)0;
}

void hal_zigbee_start_network_steering_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE));
  CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_start_network_steering_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_start_network_steering_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_start_network_steering_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_start_network_steering_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void hal_zigbee_start_network_steering_AddCallback(CMOCK_hal_zigbee_start_network_steering_CALLBACK Callback)
{
  Mock.hal_zigbee_start_network_steering_IgnoreBool = (char)0;
  Mock.hal_zigbee_start_network_steering_CallbackBool = (char)1;
  Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer = Callback;
}

void hal_zigbee_start_network_steering_Stub(CMOCK_hal_zigbee_start_network_steering_CALLBACK Callback)
{
  Mock.hal_zigbee_start_network_steering_IgnoreBool = (char)0;
  Mock.hal_zigbee_start_network_steering_CallbackBool = (char)0;
  Mock.hal_zigbee_start_network_steering_CallbackFunctionPointer = Callback;
}

void hal_zigbee_set_image_type(uint16_t image_type)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_set_image_type);
  cmock_call_instance = (CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_set_image_type_CallInstance);
  Mock.hal_zigbee_set_image_type_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_set_image_type_CallInstance);
  if (Mock.hal_zigbee_set_image_type_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_set_image_type_CallbackBool &&
      Mock.hal_zigbee_set_image_type_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_set_image_type_CallbackFunctionPointer(image_type, Mock.hal_zigbee_set_image_type_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_set_image_type,CMockString_image_type);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_image_type, image_type, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_set_image_type_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_set_image_type_CallbackFunctionPointer(image_type, Mock.hal_zigbee_set_image_type_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_set_image_type(CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE* cmock_call_instance, uint16_t image_type);
void CMockExpectParameters_hal_zigbee_set_image_type(CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE* cmock_call_instance, uint16_t image_type)
{
  cmock_call_instance->Expected_image_type = image_type;
}

void hal_zigbee_set_image_type_CMockIgnore(void)
{
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)1;
}

void hal_zigbee_set_image_type_CMockStopIgnore(void)
{
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)0;
}

void hal_zigbee_set_image_type_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE));
  CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_set_image_type_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_set_image_type_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_set_image_type_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t image_type)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE));
  CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_set_image_type_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_set_image_type_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_set_image_type_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_set_image_type(cmock_call_instance, image_type);
}

void hal_zigbee_set_image_type_AddCallback(CMOCK_hal_zigbee_set_image_type_CALLBACK Callback)
{
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)0;
  Mock.hal_zigbee_set_image_type_CallbackBool = (char)1;
  Mock.hal_zigbee_set_image_type_CallbackFunctionPointer = Callback;
}

void hal_zigbee_set_image_type_Stub(CMOCK_hal_zigbee_set_image_type_CALLBACK Callback)
{
  Mock.hal_zigbee_set_image_type_IgnoreBool = (char)0;
  Mock.hal_zigbee_set_image_type_CallbackBool = (char)0;
  Mock.hal_zigbee_set_image_type_CallbackFunctionPointer = Callback;
}

void hal_zigbee_notify_attribute_changed(uint8_t endpoint, uint16_t cluster_id, uint16_t attribute_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_notify_attribute_changed);
  cmock_call_instance = (CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_notify_attribute_changed_CallInstance);
  Mock.hal_zigbee_notify_attribute_changed_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_notify_attribute_changed_CallInstance);
  if (Mock.hal_zigbee_notify_attribute_changed_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_notify_attribute_changed_CallbackBool &&
      Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer(endpoint, cluster_id, attribute_id, Mock.hal_zigbee_notify_attribute_changed_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_notify_attribute_changed,CMockString_endpoint);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_endpoint, endpoint, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_notify_attribute_changed,CMockString_cluster_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cluster_id, cluster_id, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_notify_attribute_changed,CMockString_attribute_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_attribute_id, attribute_id, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer(endpoint, cluster_id, attribute_id, Mock.hal_zigbee_notify_attribute_changed_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_notify_attribute_changed(CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE* cmock_call_instance, uint8_t endpoint, uint16_t cluster_id, uint16_t attribute_id);
void CMockExpectParameters_hal_zigbee_notify_attribute_changed(CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE* cmock_call_instance, uint8_t endpoint, uint16_t cluster_id, uint16_t attribute_id)
{
  cmock_call_instance->Expected_endpoint = endpoint;
  cmock_call_instance->Expected_cluster_id = cluster_id;
  cmock_call_instance->Expected_attribute_id = attribute_id;
}

void hal_zigbee_notify_attribute_changed_CMockIgnore(void)
{
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)1;
}

void hal_zigbee_notify_attribute_changed_CMockStopIgnore(void)
{
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)0;
}

void hal_zigbee_notify_attribute_changed_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE));
  CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_notify_attribute_changed_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_notify_attribute_changed_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_notify_attribute_changed_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t endpoint, uint16_t cluster_id, uint16_t attribute_id)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE));
  CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_notify_attribute_changed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_notify_attribute_changed_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_notify_attribute_changed_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_notify_attribute_changed(cmock_call_instance, endpoint, cluster_id, attribute_id);
}

void hal_zigbee_notify_attribute_changed_AddCallback(CMOCK_hal_zigbee_notify_attribute_changed_CALLBACK Callback)
{
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)0;
  Mock.hal_zigbee_notify_attribute_changed_CallbackBool = (char)1;
  Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer = Callback;
}

void hal_zigbee_notify_attribute_changed_Stub(CMOCK_hal_zigbee_notify_attribute_changed_CALLBACK Callback)
{
  Mock.hal_zigbee_notify_attribute_changed_IgnoreBool = (char)0;
  Mock.hal_zigbee_notify_attribute_changed_CallbackBool = (char)0;
  Mock.hal_zigbee_notify_attribute_changed_CallbackFunctionPointer = Callback;
}

void hal_zigbee_register_on_attribute_change_callback(hal_attribute_change_callback_t callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_register_on_attribute_change_callback);
  cmock_call_instance = (CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance);
  Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance);
  if (Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_register_on_attribute_change_callback_CallbackBool &&
      Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer(callback, Mock.hal_zigbee_register_on_attribute_change_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_register_on_attribute_change_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(hal_attribute_change_callback_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer(callback, Mock.hal_zigbee_register_on_attribute_change_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_register_on_attribute_change_callback(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE* cmock_call_instance, hal_attribute_change_callback_t callback);
void CMockExpectParameters_hal_zigbee_register_on_attribute_change_callback(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE* cmock_call_instance, hal_attribute_change_callback_t callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(hal_attribute_change_callback_t[sizeof(callback) == sizeof(hal_attribute_change_callback_t) ? 1 : -1])); /* add hal_attribute_change_callback_t to :treat_as_array if this causes an error */
}

void hal_zigbee_register_on_attribute_change_callback_CMockIgnore(void)
{
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)1;
}

void hal_zigbee_register_on_attribute_change_callback_CMockStopIgnore(void)
{
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)0;
}

void hal_zigbee_register_on_attribute_change_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE));
  CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_register_on_attribute_change_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_attribute_change_callback_t callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE));
  CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_register_on_attribute_change_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_register_on_attribute_change_callback_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_register_on_attribute_change_callback(cmock_call_instance, callback);
}

void hal_zigbee_register_on_attribute_change_callback_AddCallback(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALLBACK Callback)
{
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)0;
  Mock.hal_zigbee_register_on_attribute_change_callback_CallbackBool = (char)1;
  Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer = Callback;
}

void hal_zigbee_register_on_attribute_change_callback_Stub(CMOCK_hal_zigbee_register_on_attribute_change_callback_CALLBACK Callback)
{
  Mock.hal_zigbee_register_on_attribute_change_callback_IgnoreBool = (char)0;
  Mock.hal_zigbee_register_on_attribute_change_callback_CallbackBool = (char)0;
  Mock.hal_zigbee_register_on_attribute_change_callback_CallbackFunctionPointer = Callback;
}

hal_zigbee_status_t hal_zigbee_send_cmd_to_bindings(const hal_zigbee_cmd* cmd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_send_cmd_to_bindings);
  cmock_call_instance = (CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance);
  Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance);
  if (Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_zigbee_send_cmd_to_bindings_FinalReturn;
    memcpy((void*)(&Mock.hal_zigbee_send_cmd_to_bindings_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(hal_zigbee_status_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_zigbee_send_cmd_to_bindings_CallbackBool &&
      Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer != NULL)
  {
    hal_zigbee_status_t cmock_cb_ret = Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer(cmd, Mock.hal_zigbee_send_cmd_to_bindings_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_cmd_to_bindings,CMockString_cmd);
    if (cmock_call_instance->Expected_cmd == NULL)
      { UNITY_TEST_ASSERT_NULL(cmd, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_cmd), (void*)(cmd), sizeof(const hal_zigbee_cmd), cmock_call_instance->Expected_cmd_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer(cmd, Mock.hal_zigbee_send_cmd_to_bindings_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_hal_zigbee_send_cmd_to_bindings(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance, const hal_zigbee_cmd* cmd, int cmd_Depth);
void CMockExpectParameters_hal_zigbee_send_cmd_to_bindings(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance, const hal_zigbee_cmd* cmd, int cmd_Depth)
{
  cmock_call_instance->Expected_cmd = cmd;
  cmock_call_instance->Expected_cmd_Depth = cmd_Depth;
}

void hal_zigbee_send_cmd_to_bindings_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)1;
}

void hal_zigbee_send_cmd_to_bindings_CMockStopIgnore(void)
{
  if(Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool)
    Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance);
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
}

void hal_zigbee_send_cmd_to_bindings_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_send_cmd_to_bindings_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const hal_zigbee_cmd* cmd, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_send_cmd_to_bindings(cmock_call_instance, cmd, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_zigbee_status_t[sizeof(cmock_to_return) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
}

void hal_zigbee_send_cmd_to_bindings_AddCallback(CMOCK_hal_zigbee_send_cmd_to_bindings_CALLBACK Callback)
{
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_cmd_to_bindings_CallbackBool = (char)1;
  Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer = Callback;
}

void hal_zigbee_send_cmd_to_bindings_Stub(CMOCK_hal_zigbee_send_cmd_to_bindings_CALLBACK Callback)
{
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_cmd_to_bindings_CallbackBool = (char)0;
  Mock.hal_zigbee_send_cmd_to_bindings_CallbackFunctionPointer = Callback;
}

void hal_zigbee_send_cmd_to_bindings_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const hal_zigbee_cmd* cmd, int cmd_Depth, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_cmd_to_bindings_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_cmd_to_bindings_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_cmd_to_bindings_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_cmd_to_bindings_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_send_cmd_to_bindings(cmock_call_instance, cmd, cmd_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

hal_zigbee_status_t hal_zigbee_send_report_attr(uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, uint8_t zcl_type_id, const void* value, uint8_t value_len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_send_report_attr);
  cmock_call_instance = (CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_send_report_attr_CallInstance);
  Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_report_attr_CallInstance);
  if (Mock.hal_zigbee_send_report_attr_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_zigbee_send_report_attr_FinalReturn;
    memcpy((void*)(&Mock.hal_zigbee_send_report_attr_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(hal_zigbee_status_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_zigbee_send_report_attr_CallbackBool &&
      Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer != NULL)
  {
    hal_zigbee_status_t cmock_cb_ret = Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer(endpoint, cluster_id, attr_id, zcl_type_id, value, value_len, Mock.hal_zigbee_send_report_attr_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_endpoint);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_endpoint, endpoint, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_cluster_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cluster_id, cluster_id, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_attr_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_attr_id, attr_id, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_zcl_type_id);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_zcl_type_id, zcl_type_id, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_value);
    if (cmock_call_instance->Expected_value == NULL)
      { UNITY_TEST_ASSERT_NULL(value, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_value, value, cmock_call_instance->Expected_value_Depth, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_send_report_attr,CMockString_value_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_value_len, value_len, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer(endpoint, cluster_id, attr_id, zcl_type_id, value, value_len, Mock.hal_zigbee_send_report_attr_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_hal_zigbee_send_report_attr(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, uint8_t zcl_type_id, const void* value, int value_Depth, uint8_t value_len);
void CMockExpectParameters_hal_zigbee_send_report_attr(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, uint8_t zcl_type_id, const void* value, int value_Depth, uint8_t value_len)
{
  cmock_call_instance->Expected_endpoint = endpoint;
  cmock_call_instance->Expected_cluster_id = cluster_id;
  cmock_call_instance->Expected_attr_id = attr_id;
  cmock_call_instance->Expected_zcl_type_id = zcl_type_id;
  cmock_call_instance->Expected_value = value;
  cmock_call_instance->Expected_value_Depth = value_Depth;
  cmock_call_instance->Expected_value_len = value_len;
}

void hal_zigbee_send_report_attr_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_report_attr_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)1;
}

void hal_zigbee_send_report_attr_CMockStopIgnore(void)
{
  if(Mock.hal_zigbee_send_report_attr_IgnoreBool)
    Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_report_attr_CallInstance);
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
}

void hal_zigbee_send_report_attr_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_report_attr_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_send_report_attr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, uint8_t zcl_type_id, const void* value, uint8_t value_len, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_report_attr_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_send_report_attr(cmock_call_instance, endpoint, cluster_id, attr_id, zcl_type_id, value, 1, value_len);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_zigbee_status_t[sizeof(cmock_to_return) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
}

void hal_zigbee_send_report_attr_AddCallback(CMOCK_hal_zigbee_send_report_attr_CALLBACK Callback)
{
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_report_attr_CallbackBool = (char)1;
  Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer = Callback;
}

void hal_zigbee_send_report_attr_Stub(CMOCK_hal_zigbee_send_report_attr_CALLBACK Callback)
{
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_report_attr_CallbackBool = (char)0;
  Mock.hal_zigbee_send_report_attr_CallbackFunctionPointer = Callback;
}

void hal_zigbee_send_report_attr_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t endpoint, uint16_t cluster_id, uint16_t attr_id, uint8_t zcl_type_id, const void* value, int value_Depth, uint8_t value_len, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_report_attr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_report_attr_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_report_attr_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_report_attr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_send_report_attr(cmock_call_instance, endpoint, cluster_id, attr_id, zcl_type_id, value, value_Depth, value_len);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

hal_zigbee_status_t hal_zigbee_send_announce(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_send_announce_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_send_announce);
  cmock_call_instance = (CMOCK_hal_zigbee_send_announce_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_send_announce_CallInstance);
  Mock.hal_zigbee_send_announce_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_announce_CallInstance);
  if (Mock.hal_zigbee_send_announce_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_zigbee_send_announce_FinalReturn;
    memcpy((void*)(&Mock.hal_zigbee_send_announce_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(hal_zigbee_status_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_zigbee_send_announce_CallbackBool &&
      Mock.hal_zigbee_send_announce_CallbackFunctionPointer != NULL)
  {
    hal_zigbee_status_t cmock_cb_ret = Mock.hal_zigbee_send_announce_CallbackFunctionPointer(Mock.hal_zigbee_send_announce_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_zigbee_send_announce_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_zigbee_send_announce_CallbackFunctionPointer(Mock.hal_zigbee_send_announce_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void hal_zigbee_send_announce_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_announce_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_announce_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_announce_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_announce_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_announce_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)1;
}

void hal_zigbee_send_announce_CMockStopIgnore(void)
{
  if(Mock.hal_zigbee_send_announce_IgnoreBool)
    Mock.hal_zigbee_send_announce_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_send_announce_CallInstance);
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)0;
}

void hal_zigbee_send_announce_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, hal_zigbee_status_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_send_announce_CALL_INSTANCE));
  CMOCK_hal_zigbee_send_announce_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_send_announce_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_send_announce_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_send_announce_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_zigbee_status_t[sizeof(cmock_to_return) == sizeof(hal_zigbee_status_t) ? 1 : -1])); /* add hal_zigbee_status_t to :treat_as_array if this causes an error */
}

void hal_zigbee_send_announce_AddCallback(CMOCK_hal_zigbee_send_announce_CALLBACK Callback)
{
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_announce_CallbackBool = (char)1;
  Mock.hal_zigbee_send_announce_CallbackFunctionPointer = Callback;
}

void hal_zigbee_send_announce_Stub(CMOCK_hal_zigbee_send_announce_CALLBACK Callback)
{
  Mock.hal_zigbee_send_announce_IgnoreBool = (char)0;
  Mock.hal_zigbee_send_announce_CallbackBool = (char)0;
  Mock.hal_zigbee_send_announce_CallbackFunctionPointer = Callback;
}

void hal_zigbee_register_on_zcl_activity_callback(hal_zcl_activity_callback_t callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_register_on_zcl_activity_callback);
  cmock_call_instance = (CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance);
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance);
  if (Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackBool &&
      Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer(callback, Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_register_on_zcl_activity_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(hal_zcl_activity_callback_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer(callback, Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_register_on_zcl_activity_callback(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE* cmock_call_instance, hal_zcl_activity_callback_t callback);
void CMockExpectParameters_hal_zigbee_register_on_zcl_activity_callback(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE* cmock_call_instance, hal_zcl_activity_callback_t callback)
{
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(hal_zcl_activity_callback_t[sizeof(callback) == sizeof(hal_zcl_activity_callback_t) ? 1 : -1])); /* add hal_zcl_activity_callback_t to :treat_as_array if this causes an error */
}

void hal_zigbee_register_on_zcl_activity_callback_CMockIgnore(void)
{
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)1;
}

void hal_zigbee_register_on_zcl_activity_callback_CMockStopIgnore(void)
{
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)0;
}

void hal_zigbee_register_on_zcl_activity_callback_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE));
  CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_register_on_zcl_activity_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_zcl_activity_callback_t callback)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE));
  CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_register_on_zcl_activity_callback_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_register_on_zcl_activity_callback(cmock_call_instance, callback);
}

void hal_zigbee_register_on_zcl_activity_callback_AddCallback(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALLBACK Callback)
{
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)0;
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackBool = (char)1;
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer = Callback;
}

void hal_zigbee_register_on_zcl_activity_callback_Stub(CMOCK_hal_zigbee_register_on_zcl_activity_callback_CALLBACK Callback)
{
  Mock.hal_zigbee_register_on_zcl_activity_callback_IgnoreBool = (char)0;
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackBool = (char)0;
  Mock.hal_zigbee_register_on_zcl_activity_callback_CallbackFunctionPointer = Callback;
}

void hal_zigbee_set_poll_rate_ms(uint32_t poll_rate_ms)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_set_poll_rate_ms);
  cmock_call_instance = (CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_set_poll_rate_ms_CallInstance);
  Mock.hal_zigbee_set_poll_rate_ms_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_set_poll_rate_ms_CallInstance);
  if (Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.hal_zigbee_set_poll_rate_ms_CallbackBool &&
      Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer(poll_rate_ms, Mock.hal_zigbee_set_poll_rate_ms_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  {
    UNITY_SET_DETAILS(CMockString_hal_zigbee_set_poll_rate_ms,CMockString_poll_rate_ms);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_poll_rate_ms, poll_rate_ms, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer(poll_rate_ms, Mock.hal_zigbee_set_poll_rate_ms_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_zigbee_set_poll_rate_ms(CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE* cmock_call_instance, uint32_t poll_rate_ms);
void CMockExpectParameters_hal_zigbee_set_poll_rate_ms(CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE* cmock_call_instance, uint32_t poll_rate_ms)
{
  cmock_call_instance->Expected_poll_rate_ms = poll_rate_ms;
}

void hal_zigbee_set_poll_rate_ms_CMockIgnore(void)
{
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)1;
}

void hal_zigbee_set_poll_rate_ms_CMockStopIgnore(void)
{
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)0;
}

void hal_zigbee_set_poll_rate_ms_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE));
  CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_set_poll_rate_ms_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_set_poll_rate_ms_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void hal_zigbee_set_poll_rate_ms_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t poll_rate_ms)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE));
  CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_set_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_set_poll_rate_ms_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_set_poll_rate_ms_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_hal_zigbee_set_poll_rate_ms(cmock_call_instance, poll_rate_ms);
}

void hal_zigbee_set_poll_rate_ms_AddCallback(CMOCK_hal_zigbee_set_poll_rate_ms_CALLBACK Callback)
{
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)0;
  Mock.hal_zigbee_set_poll_rate_ms_CallbackBool = (char)1;
  Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer = Callback;
}

void hal_zigbee_set_poll_rate_ms_Stub(CMOCK_hal_zigbee_set_poll_rate_ms_CALLBACK Callback)
{
  Mock.hal_zigbee_set_poll_rate_ms_IgnoreBool = (char)0;
  Mock.hal_zigbee_set_poll_rate_ms_CallbackBool = (char)0;
  Mock.hal_zigbee_set_poll_rate_ms_CallbackFunctionPointer = Callback;
}

uint32_t hal_zigbee_get_poll_rate_ms(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_zigbee_get_poll_rate_ms);
  cmock_call_instance = (CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_zigbee_get_poll_rate_ms_CallInstance);
  Mock.hal_zigbee_get_poll_rate_ms_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_get_poll_rate_ms_CallInstance);
  if (Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.hal_zigbee_get_poll_rate_ms_FinalReturn;
    Mock.hal_zigbee_get_poll_rate_ms_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.hal_zigbee_get_poll_rate_ms_CallbackBool &&
      Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer(Mock.hal_zigbee_get_poll_rate_ms_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer(Mock.hal_zigbee_get_poll_rate_ms_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void hal_zigbee_get_poll_rate_ms_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE));
  CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_get_poll_rate_ms_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_get_poll_rate_ms_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)1;
}

void hal_zigbee_get_poll_rate_ms_CMockStopIgnore(void)
{
  if(Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool)
    Mock.hal_zigbee_get_poll_rate_ms_CallInstance = CMock_Guts_MemNext(Mock.hal_zigbee_get_poll_rate_ms_CallInstance);
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)0;
}

void hal_zigbee_get_poll_rate_ms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE));
  CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_zigbee_get_poll_rate_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_zigbee_get_poll_rate_ms_CallInstance = CMock_Guts_MemChain(Mock.hal_zigbee_get_poll_rate_ms_CallInstance, cmock_guts_index);
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void hal_zigbee_get_poll_rate_ms_AddCallback(CMOCK_hal_zigbee_get_poll_rate_ms_CALLBACK Callback)
{
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)0;
  Mock.hal_zigbee_get_poll_rate_ms_CallbackBool = (char)1;
  Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer = Callback;
}

void hal_zigbee_get_poll_rate_ms_Stub(CMOCK_hal_zigbee_get_poll_rate_ms_CALLBACK Callback)
{
  Mock.hal_zigbee_get_poll_rate_ms_IgnoreBool = (char)0;
  Mock.hal_zigbee_get_poll_rate_ms_CallbackBool = (char)0;
  Mock.hal_zigbee_get_poll_rate_ms_CallbackFunctionPointer = Callback;
}

