version: '3.8'

services:
  build:
    build: .
    volumes:
      - .:/workspace
      - build-cache:/workspace/build
      - sdk-cache:/workspace/sdk
      - toolchain-cache:/workspace/toolchain
    working_dir: /workspace
    environment:
      - TERM=xterm-256color
    stdin_open: true
    tty: true

volumes:
  build-cache:
  sdk-cache:
  toolchain-cache: