/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockgpio.h"

static const char* CMockString_arg = "arg";
static const char* CMockString_callback = "callback";
static const char* CMockString_gpio_pin = "gpio_pin";
static const char* CMockString_hal_gpio_callback = "hal_gpio_callback";
static const char* CMockString_hal_gpio_clear = "hal_gpio_clear";
static const char* CMockString_hal_gpio_init = "hal_gpio_init";
static const char* CMockString_hal_gpio_parse_pin = "hal_gpio_parse_pin";
static const char* CMockString_hal_gpio_parse_pull = "hal_gpio_parse_pull";
static const char* CMockString_hal_gpio_read = "hal_gpio_read";
static const char* CMockString_hal_gpio_set = "hal_gpio_set";
static const char* CMockString_hal_gpio_unreg_callback = "hal_gpio_unreg_callback";
static const char* CMockString_is_input = "is_input";
static const char* CMockString_pull = "pull";
static const char* CMockString_pull_str = "pull_str";
static const char* CMockString_s = "s";

typedef struct _CMOCK_hal_gpio_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t Expected_gpio_pin;
  uint8_t Expected_is_input;
  hal_gpio_pull_t Expected_pull;

} CMOCK_hal_gpio_init_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_set_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t Expected_gpio_pin;

} CMOCK_hal_gpio_set_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_clear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t Expected_gpio_pin;

} CMOCK_hal_gpio_clear_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  hal_gpio_pin_t Expected_gpio_pin;

} CMOCK_hal_gpio_read_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t Expected_gpio_pin;
  gpio_callback_t Expected_callback;
  void* Expected_arg;

} CMOCK_hal_gpio_callback_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t Expected_gpio_pin;

} CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_parse_pin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pin_t ReturnVal;
  const char* Expected_s;

} CMOCK_hal_gpio_parse_pin_CALL_INSTANCE;

typedef struct _CMOCK_hal_gpio_parse_pull_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  hal_gpio_pull_t ReturnVal;
  const char* Expected_pull_str;

} CMOCK_hal_gpio_parse_pull_CALL_INSTANCE;

static struct MockgpioInstance
{
  CMOCK_MEM_INDEX_TYPE hal_gpio_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_set_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_clear_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_read_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_callback_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_unreg_callback_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_parse_pin_CallInstance;
  CMOCK_MEM_INDEX_TYPE hal_gpio_parse_pull_CallInstance;
} Mock;


void Mockgpio_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.hal_gpio_init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_set_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_set);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_clear_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_clear);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_read_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_read);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_callback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_unreg_callback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_unreg_callback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_parse_pin_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_parse_pin);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.hal_gpio_parse_pull_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_hal_gpio_parse_pull);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockgpio_Init(void)
{
  Mockgpio_Destroy();
}

void Mockgpio_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void hal_gpio_init(hal_gpio_pin_t gpio_pin, uint8_t is_input, hal_gpio_pull_t pull)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_init);
  cmock_call_instance = (CMOCK_hal_gpio_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_init_CallInstance);
  Mock.hal_gpio_init_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_init,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_init,CMockString_is_input);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_is_input, is_input, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_init,CMockString_pull);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pull), (void*)(&pull), sizeof(hal_gpio_pull_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_gpio_init(CMOCK_hal_gpio_init_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin, uint8_t is_input, hal_gpio_pull_t pull);
void CMockExpectParameters_hal_gpio_init(CMOCK_hal_gpio_init_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin, uint8_t is_input, hal_gpio_pull_t pull)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_is_input = is_input;
  memcpy((void*)(&cmock_call_instance->Expected_pull), (void*)(&pull),
         sizeof(hal_gpio_pull_t[sizeof(pull) == sizeof(hal_gpio_pull_t) ? 1 : -1])); /* add hal_gpio_pull_t to :treat_as_array if this causes an error */
}

void hal_gpio_init_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, uint8_t is_input, hal_gpio_pull_t pull)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_init_CALL_INSTANCE));
  CMOCK_hal_gpio_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_init_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_init(cmock_call_instance, gpio_pin, is_input, pull);
}

void hal_gpio_set(hal_gpio_pin_t gpio_pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_set_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_set);
  cmock_call_instance = (CMOCK_hal_gpio_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_set_CallInstance);
  Mock.hal_gpio_set_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_set_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_set,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_gpio_set(CMOCK_hal_gpio_set_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin);
void CMockExpectParameters_hal_gpio_set(CMOCK_hal_gpio_set_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
}

void hal_gpio_set_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_set_CALL_INSTANCE));
  CMOCK_hal_gpio_set_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_set_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_set_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_set_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_set(cmock_call_instance, gpio_pin);
}

void hal_gpio_clear(hal_gpio_pin_t gpio_pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_clear_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_clear);
  cmock_call_instance = (CMOCK_hal_gpio_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_clear_CallInstance);
  Mock.hal_gpio_clear_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_clear_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_clear,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_gpio_clear(CMOCK_hal_gpio_clear_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin);
void CMockExpectParameters_hal_gpio_clear(CMOCK_hal_gpio_clear_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
}

void hal_gpio_clear_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_clear_CALL_INSTANCE));
  CMOCK_hal_gpio_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_clear_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_clear_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_clear(cmock_call_instance, gpio_pin);
}

uint8_t hal_gpio_read(hal_gpio_pin_t gpio_pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_read);
  cmock_call_instance = (CMOCK_hal_gpio_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_read_CallInstance);
  Mock.hal_gpio_read_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_read_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_read,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_hal_gpio_read(CMOCK_hal_gpio_read_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin);
void CMockExpectParameters_hal_gpio_read(CMOCK_hal_gpio_read_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
}

void hal_gpio_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_read_CALL_INSTANCE));
  CMOCK_hal_gpio_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_read_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_read_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_read(cmock_call_instance, gpio_pin);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void hal_gpio_callback(hal_gpio_pin_t gpio_pin, gpio_callback_t callback, void* arg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_callback);
  cmock_call_instance = (CMOCK_hal_gpio_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_callback_CallInstance);
  Mock.hal_gpio_callback_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_callback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_callback,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_callback,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback), sizeof(gpio_callback_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_callback,CMockString_arg);
    if (cmock_call_instance->Expected_arg == NULL)
      { UNITY_TEST_ASSERT_NULL(arg, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_arg, arg, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_gpio_callback(CMOCK_hal_gpio_callback_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin, gpio_callback_t callback, void* arg);
void CMockExpectParameters_hal_gpio_callback(CMOCK_hal_gpio_callback_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin, gpio_callback_t callback, void* arg)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(gpio_callback_t[sizeof(callback) == sizeof(gpio_callback_t) ? 1 : -1])); /* add gpio_callback_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_arg = arg;
}

void hal_gpio_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, gpio_callback_t callback, void* arg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_callback_CALL_INSTANCE));
  CMOCK_hal_gpio_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_callback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_callback(cmock_call_instance, gpio_pin, callback, arg);
}

void hal_gpio_unreg_callback(hal_gpio_pin_t gpio_pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_unreg_callback);
  cmock_call_instance = (CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_unreg_callback_CallInstance);
  Mock.hal_gpio_unreg_callback_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_unreg_callback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_unreg_callback,CMockString_gpio_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin), sizeof(hal_gpio_pin_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_hal_gpio_unreg_callback(CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin);
void CMockExpectParameters_hal_gpio_unreg_callback(CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE* cmock_call_instance, hal_gpio_pin_t gpio_pin)
{
  memcpy((void*)(&cmock_call_instance->Expected_gpio_pin), (void*)(&gpio_pin),
         sizeof(hal_gpio_pin_t[sizeof(gpio_pin) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
}

void hal_gpio_unreg_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE));
  CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_unreg_callback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_unreg_callback_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_unreg_callback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_unreg_callback(cmock_call_instance, gpio_pin);
}

hal_gpio_pin_t hal_gpio_parse_pin(const char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_parse_pin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_parse_pin);
  cmock_call_instance = (CMOCK_hal_gpio_parse_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_parse_pin_CallInstance);
  Mock.hal_gpio_parse_pin_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_parse_pin_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_parse_pin,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_hal_gpio_parse_pin(CMOCK_hal_gpio_parse_pin_CALL_INSTANCE* cmock_call_instance, const char* s);
void CMockExpectParameters_hal_gpio_parse_pin(CMOCK_hal_gpio_parse_pin_CALL_INSTANCE* cmock_call_instance, const char* s)
{
  cmock_call_instance->Expected_s = s;
}

void hal_gpio_parse_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* s, hal_gpio_pin_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_parse_pin_CALL_INSTANCE));
  CMOCK_hal_gpio_parse_pin_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_parse_pin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_parse_pin_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_parse_pin_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_parse_pin(cmock_call_instance, s);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_gpio_pin_t[sizeof(cmock_to_return) == sizeof(hal_gpio_pin_t) ? 1 : -1])); /* add hal_gpio_pin_t to :treat_as_array if this causes an error */
}

hal_gpio_pull_t hal_gpio_parse_pull(const char* pull_str)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_hal_gpio_parse_pull_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_hal_gpio_parse_pull);
  cmock_call_instance = (CMOCK_hal_gpio_parse_pull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.hal_gpio_parse_pull_CallInstance);
  Mock.hal_gpio_parse_pull_CallInstance = CMock_Guts_MemNext(Mock.hal_gpio_parse_pull_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_hal_gpio_parse_pull,CMockString_pull_str);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_pull_str, pull_str, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_hal_gpio_parse_pull(CMOCK_hal_gpio_parse_pull_CALL_INSTANCE* cmock_call_instance, const char* pull_str);
void CMockExpectParameters_hal_gpio_parse_pull(CMOCK_hal_gpio_parse_pull_CALL_INSTANCE* cmock_call_instance, const char* pull_str)
{
  cmock_call_instance->Expected_pull_str = pull_str;
}

void hal_gpio_parse_pull_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* pull_str, hal_gpio_pull_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_hal_gpio_parse_pull_CALL_INSTANCE));
  CMOCK_hal_gpio_parse_pull_CALL_INSTANCE* cmock_call_instance = (CMOCK_hal_gpio_parse_pull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.hal_gpio_parse_pull_CallInstance = CMock_Guts_MemChain(Mock.hal_gpio_parse_pull_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_hal_gpio_parse_pull(cmock_call_instance, pull_str);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(hal_gpio_pull_t[sizeof(cmock_to_return) == sizeof(hal_gpio_pull_t) ? 1 : -1])); /* add hal_gpio_pull_t to :treat_as_array if this causes an error */
}

