/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKGPIO_H
#define _MOCKGPIO_H

#include "unity.h"
#include "hal/gpio.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockgpio_Init(void);
void Mockgpio_Destroy(void);
void Mockgpio_Verify(void);




#define hal_gpio_init_ExpectAndReturn(gpio_pin, is_input, pull, cmock_retval) TEST_FAIL_MESSAGE("hal_gpio_init requires _Expect (not AndReturn)");
#define hal_gpio_init_Expect(gpio_pin, is_input, pull) hal_gpio_init_CMockExpect(__LINE__, gpio_pin, is_input, pull)
void hal_gpio_init_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, uint8_t is_input, hal_gpio_pull_t pull);
#define hal_gpio_set_ExpectAndReturn(gpio_pin, cmock_retval) TEST_FAIL_MESSAGE("hal_gpio_set requires _Expect (not AndReturn)");
#define hal_gpio_set_Expect(gpio_pin) hal_gpio_set_CMockExpect(__LINE__, gpio_pin)
void hal_gpio_set_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin);
#define hal_gpio_clear_ExpectAndReturn(gpio_pin, cmock_retval) TEST_FAIL_MESSAGE("hal_gpio_clear requires _Expect (not AndReturn)");
#define hal_gpio_clear_Expect(gpio_pin) hal_gpio_clear_CMockExpect(__LINE__, gpio_pin)
void hal_gpio_clear_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin);
#define hal_gpio_read_Expect(gpio_pin) TEST_FAIL_MESSAGE("hal_gpio_read requires _ExpectAndReturn");
#define hal_gpio_read_ExpectAndReturn(gpio_pin, cmock_retval) hal_gpio_read_CMockExpectAndReturn(__LINE__, gpio_pin, cmock_retval)
void hal_gpio_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, uint8_t cmock_to_return);
#define hal_gpio_callback_ExpectAndReturn(gpio_pin, callback, arg, cmock_retval) TEST_FAIL_MESSAGE("hal_gpio_callback requires _Expect (not AndReturn)");
#define hal_gpio_callback_Expect(gpio_pin, callback, arg) hal_gpio_callback_CMockExpect(__LINE__, gpio_pin, callback, arg)
void hal_gpio_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin, gpio_callback_t callback, void* arg);
#define hal_gpio_unreg_callback_ExpectAndReturn(gpio_pin, cmock_retval) TEST_FAIL_MESSAGE("hal_gpio_unreg_callback requires _Expect (not AndReturn)");
#define hal_gpio_unreg_callback_Expect(gpio_pin) hal_gpio_unreg_callback_CMockExpect(__LINE__, gpio_pin)
void hal_gpio_unreg_callback_CMockExpect(UNITY_LINE_TYPE cmock_line, hal_gpio_pin_t gpio_pin);
#define hal_gpio_parse_pin_Expect(s) TEST_FAIL_MESSAGE("hal_gpio_parse_pin requires _ExpectAndReturn");
#define hal_gpio_parse_pin_ExpectAndReturn(s, cmock_retval) hal_gpio_parse_pin_CMockExpectAndReturn(__LINE__, s, cmock_retval)
void hal_gpio_parse_pin_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* s, hal_gpio_pin_t cmock_to_return);
#define hal_gpio_parse_pull_Expect(pull_str) TEST_FAIL_MESSAGE("hal_gpio_parse_pull requires _ExpectAndReturn");
#define hal_gpio_parse_pull_ExpectAndReturn(pull_str, cmock_retval) hal_gpio_parse_pull_CMockExpectAndReturn(__LINE__, pull_str, cmock_retval)
void hal_gpio_parse_pull_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const char* pull_str, hal_gpio_pull_t cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
