/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "zigbee/step_command_handler.h"
#include "Mocktimer.h"
#include "Mocktasks.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_first_call_to_step_up_triggers_callback(void);
extern void test_first_call_to_step_down_triggers_callback(void);
extern void test_step_up_calls_very_close_together_are_debounced(void);
extern void test_step_down_calls_very_close_together_are_debounced(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mocktimer_Init();
  Mocktasks_Init();
}
static void CMock_Verify(void)
{
  Mocktimer_Verify();
  Mocktasks_Verify();
}
static void CMock_Destroy(void)
{
  Mocktimer_Destroy();
  Mocktasks_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_step_command_handler.c");
  run_test(test_first_call_to_step_up_triggers_callback, "test_first_call_to_step_up_triggers_callback", 36);
  run_test(test_first_call_to_step_down_triggers_callback, "test_first_call_to_step_down_triggers_callback", 52);
  run_test(test_step_up_calls_very_close_together_are_debounced, "test_step_up_calls_very_close_together_are_debounced", 68);
  run_test(test_step_down_calls_very_close_together_are_debounced, "test_step_down_calls_very_close_together_are_debounced", 96);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
