/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "zigbee/encoder_cluster.h"
#include "zigbee/consts.h"
#include "Mockzigbee.h"
#include "Mockstep_command_handler.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_encoder_is_clicked(void);
extern void test_encoder_is_rotated_cw(void);
extern void test_encoder_is_rotated_ccw(void);
extern void test_brightness_step_command_handler_callback_with_positive_value(void);
extern void test_brightness_step_command_handler_callback_with_negative_value(void);
extern void test_encoder_is_rotated_cw_while_pressed(void);
extern void test_encoder_is_rotated_ccw_while_pressed(void);
extern void test_color_temp_step_command_handler_callback_with_positive_value(void);
extern void test_color_temp_step_command_handler_callback_with_negative_value(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockzigbee_Init();
  Mockstep_command_handler_Init();
}
static void CMock_Verify(void)
{
  Mockzigbee_Verify();
  Mockstep_command_handler_Verify();
}
static void CMock_Destroy(void)
{
  Mockzigbee_Destroy();
  Mockstep_command_handler_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_encoder_cluster.c");
  run_test(test_encoder_is_clicked, "test_encoder_is_clicked", 71);
  run_test(test_encoder_is_rotated_cw, "test_encoder_is_rotated_cw", 78);
  run_test(test_encoder_is_rotated_ccw, "test_encoder_is_rotated_ccw", 90);
  run_test(test_brightness_step_command_handler_callback_with_positive_value, "test_brightness_step_command_handler_callback_with_positive_value", 102);
  run_test(test_brightness_step_command_handler_callback_with_negative_value, "test_brightness_step_command_handler_callback_with_negative_value", 135);
  run_test(test_encoder_is_rotated_cw_while_pressed, "test_encoder_is_rotated_cw_while_pressed", 168);
  run_test(test_encoder_is_rotated_ccw_while_pressed, "test_encoder_is_rotated_ccw_while_pressed", 180);
  run_test(test_color_temp_step_command_handler_callback_with_positive_value, "test_color_temp_step_command_handler_callback_with_positive_value", 192);
  run_test(test_color_temp_step_command_handler_callback_with_negative_value, "test_color_temp_step_command_handler_callback_with_negative_value", 234);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
