/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "base_components/encoder.h"
#include "gpio_callback_helper.h"
#include "Mockgpio.h"
#include "Mocktimer.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_encoder_init_sets_states(void);
extern void test_encoder_pin_a_changing_before_pin_b(void);
extern void test_encoder_pin_a_changing_after_pin_b(void);
extern void test_encoder_pin_b_changing_before_pin_a(void);
extern void test_encoder_pin_b_changing_after_pin_a(void);
extern void test_encoder_pin_sw_changes_to_low(void);
extern void test_encoder_pin_sw_changes_to_high(void);
extern void test_encoder_pin_sw_changes_to_low_noisy(void);
extern void test_encoder_pin_a_changing_before_pin_b_while_sw_is_low(void);
extern void test_encoder_pin_b_changing_before_pin_a_while_sw_is_low(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockgpio_Init();
  Mocktimer_Init();
}
static void CMock_Verify(void)
{
  Mockgpio_Verify();
  Mocktimer_Verify();
}
static void CMock_Destroy(void)
{
  Mockgpio_Destroy();
  Mocktimer_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_encoder.c");
  run_test(test_encoder_init_sets_states, "test_encoder_init_sets_states", 54);
  run_test(test_encoder_pin_a_changing_before_pin_b, "test_encoder_pin_a_changing_before_pin_b", 115);
  run_test(test_encoder_pin_a_changing_after_pin_b, "test_encoder_pin_a_changing_after_pin_b", 133);
  run_test(test_encoder_pin_b_changing_before_pin_a, "test_encoder_pin_b_changing_before_pin_a", 151);
  run_test(test_encoder_pin_b_changing_after_pin_a, "test_encoder_pin_b_changing_after_pin_a", 169);
  run_test(test_encoder_pin_sw_changes_to_low, "test_encoder_pin_sw_changes_to_low", 186);
  run_test(test_encoder_pin_sw_changes_to_high, "test_encoder_pin_sw_changes_to_high", 205);
  run_test(test_encoder_pin_sw_changes_to_low_noisy, "test_encoder_pin_sw_changes_to_low_noisy", 225);
  run_test(test_encoder_pin_a_changing_before_pin_b_while_sw_is_low, "test_encoder_pin_a_changing_before_pin_b_while_sw_is_low", 251);
  run_test(test_encoder_pin_b_changing_before_pin_a_while_sw_is_low, "test_encoder_pin_b_changing_before_pin_a_while_sw_is_low", 271);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
